### ISSUE TITLE
这是bug吗

### ISSUE THREAD

**Issue by xcsweb** [thx/gogocode#1]
![image](https://user-images.githubusercontent.com/20693737/110913359-01750280-8350-11eb-8200-1c426c9d8770.png)
![image](https://user-images.githubusercontent.com/20693737/110913425-1a7db380-8350-11eb-809f-03f573f85ad4.png)
两种写法

**Comment by shuerguo999** [comment]
不好意思，文档有一点问题，我会立刻更新。
第一个写法需要改成：
$(code).find('var $_$1 = $_$2').replace('var $_$1 = $_$2', 'let $_$1 = $_$2').generate()
原因是：存在多个通配符时需要附加key
第二个写法不支持哈～因为replace会将你输入的内容转为ast节点，再从ast中搜索，单独的var和单独的let不能被转为合法的ast节点。但是你的写法我们会考虑以更好的方式兼容哦～
感谢
