### ISSUE TITLE
Bug Report From Playground: 对`export default {$$$}`进行替换后，是不是有点问题？

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#100]
- version: 1.0.39
- playground demo: [link](https://play.gogocode.io/?v=1.0.39#code/N4IglgdgDgrgLgYQPYBMCmIBcI0A8pIBOcABOgGYCGMANqcAL4DcIANCAO5EDWy6WIcjAgBjOGCQQScQpQgBnckQC2ACnJgaaAJIQlrEpShgDSKOMnyAlCWAAdKSRGXSAEhIBeQ8YB0AcyQA53QHEicXEnkkGEIRNE8SDS1dJR8omLjQkgB6bJJCNDgYqQBPaMJpWQUlQmU0FHD0EgALNAKsgqLCKVdVdNi0Kx8CqBpKONUAcjwCYjI0Klp6VxWGSYNp-CJSCmo6WxXXAxRKOEpMRjWhvzQINtO0VSsHBgc2cGh4ABk5PwE4EpQNDyESEMDmd7NSjyAAKnXEbSwMhgaHY8hgACMAGpgNAcAAqgIw2BkaAwDCAA)
- detail desc:

**Comment by shuerguo999** [comment]
1.0.40 fix
