### ISSUE TITLE
esbuild-dynamic-import-plugin 相比于直接使用 esbuild + babel + babel-plugin-import(post) 性能高低？

### ISSUE THREAD

**Issue by imcuttle** [thx/gogocode#102]
在我的场景中：在 webpack 内使用 [esbuild-loader](https://github.com/privatenumber/esbuild-loader) 来替换 babel-loader；
的确能够起到提升转换速度的作用，但是 esbuild 本身没有提供 babel-plugin-import 的功能，所以暂时是使用 esbuild-loader + babel-loader(babel-plugin-import) 来进行实现。

那么相比于以上方式，使用 esbuild-dynamic-import-plugin 会有什么性能优势吗？

查看 esbuild-dynamic-import-plugin 实现，也是基于 babel ast + 遍历替换 + stringify 来实现的
那么相比于直接使用 babel + babel-plugin-import(post) 来作为转换，感觉两者性能基本趋同？

**Comment by kooriko** [comment]
esbuild-dynamic-import-plugin 是面向 esbuild 项目的 babel-plugin-import 模式的插件。
所以本插件的目的在于：
1. cover 纯 esbuild 项目的动态引入场景；
2. 提升开发者从 webpack 迁移至 esbuild 的开发体验。
因此性能不是主要考虑的情形。
esbuild 性能较好原因是 go 比较快，但本插件使用的是 js 开发，因此和 babel + babel-plugin-import 的性能是趋同的。

**Comment by imcuttle** [comment]
> 2\. 性能

从 webpack 迁移至 esbuild，应该也是看中的 esbuild 的高性能，但是如果引入该插件导致性能持平的话，感觉可能不太合适
