### ISSUE TITLE
Error: Command failed, exited with code #243

### ISSUE THREAD

**Issue by jimmyli-crypto** [thx/gogocode#103]
- version: 0.2.23
- playground demo:
- your description:
`gogocode -s ./icon.vue -t gogocode-plugin-vue -o ./out-icon.vue`
I execute this command in the directory that needs to be converted, and an error is reported
![image](https://user-images.githubusercontent.com/89769619/141118019-c3af40c5-6ca7-4f2d-818e-7b8786edab1c.png)

**Comment by wudi3** [comment]
execute this command
`npm install gogocode-plugin-vue -g`
before execute
`gogocode -s ./icon.vue -t gogocode-plugin-vue -o ./out-icon.vue`
