### ISSUE TITLE
 转换后启动项目TypeError: Cannot read property 'parseComponent' of undefined

### ISSUE THREAD

**Issue by advanceCabbage** [thx/gogocode#104]
遵循gogocode文档vue2-to-vue3升级项目，步骤执行完毕，启动项目控制台显示Syntax Error: TypeError: Cannot read property 'parseComponent' of undefined

**Comment by eyis** [comment]
> 遵循gogocode文档vue2-to-vue3升级项目，步骤执行完毕，启动项目控制台显示Syntax Error: TypeError: Cannot read property 'parseComponent' of undefined

报错的原因是 vue升级后 vue-template-compiler 中的 parseComponent 函数被删除了

解决这个问题：
1. 需要确认 package.json 中的 vue-template-compiler 是否已经替换为 @vue/compiler-sfc，否则的话需要替换，然后重新安装依赖。
2. 如果还报这个错误，则需要检查下项目引用的第三方依赖是否还有 Vue2 的版本，如果有的话需要对应更新为支持 Vue3 的版本。
