### ISSUE TITLE
可以增加获取孩子节点的api吗

### ISSUE THREAD

**Issue by quanxiaole** [thx/gogocode#105]
- version:
- playground demo:
- your description:

**Comment by shuerguo999** [comment]
支持，child find都可以
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIDGSIDOcABAIbEC8xAjADoR6EkBGlxATPSADQgDuSAE4BrZOiwgAZjAZww+YnEGlCkoQFsAFJLAAbNAEkIa7mShhTSKHPwEAlMWD1ixRkWIASNqXMA6AOZIgXjozq62JARIMII4aGw6+kZqvlExcWEA9JnEgmhwMRDEAJ7RgorKqhpoKOHoxAAWaHlh+iR5BGwemmmxaHb0Yb46ECiaAORuJORU1OMDRcS+OA16Y+PoOLqkyjaEvgAM82FuSPq+ukGaHQsup+eX-tdoBL5QO2gQcAv0AL5cvEgsDgABkVP4JHBilAXjhBGBrDwQA1SAQAAp5OByZpYJQwNC8AgwZgANTAaD4ABVoRhsEo0BhfkA
