### ISSUE TITLE
Bug Report From Playground: 复制自己然后给它添加注释时，报错

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#107]
- version: 1.0.40
- playground demo: [link](https://play.gogocode.io/?v=1.0.40#code/N4IglgdgDgrgLgYQPYBMCmIBcI4AswDOAdAIYRgC2JcaAFADogFwCeANmowDQAEcAlCC4gA7kgBOAa2TosIAGYwIAYzhgkEPuLIF5EirXlgOASQh7eJKGF5IoajQX49g9TT2WO4PACQ8AvDxWYEQA5kjhnuhuPB5ePARIMOLKaAE8RqbmSESJyaluMTwA9MU84mhwyZosSeJaOnriFGgoceg8uGgVRRVV4po+tHkpaPxFsURGECi0AOQ+APo+pORUNLQ+W-xz4+6TaCTKuIZKquqatGA0FM6u+7ElxYCbfoC-ioAOpoDftoAFSoAXNoBTiYA300AMP+AAHTAH5GgDYnQDlfhNHgA3Ej1KBItAQbyBa5oChEFEVdG0YB8FhQNCYHhzACiAA8oBUCAQLgBlODUbFouBzHgAXz2cNipR4gCezQD9foBFU0Av2r8niI+oQNAiACCzHSQyxONCaO6bNo-D2j0eeI5RAARmgmnR5UrmPqDTwrcq4KbzRI6HN6G5BQDAAD6gGnNHgeiC7UjyGjieaBr3-QDLfoB9c0Dgd2cN5cKI4iQSDgutTmvl2g2e25biE4Gg8AAMmRQnJWKSCMpxGB7CXcCQCAAFPpqbpYeQkNgENDCAgwE0ANTACoAKiSMNg4BUMNygA)
- detail desc:

before()添加会有问题，原因是没有换行，
而after()添加则无问题。

**Comment by shuerguo999** [comment]
已解决
[playground](https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcI4AswDOAdAIYRgC2JcaAFADogFwCeANmowDQAEcAlCC4gA7kgBOAa2TosIAGYwIAYzhgkEPuLIF5EirXlgOASQh7eJKGF5IoajQX49g9TT2WO4PACQ8AvDxWYEQA5kjhnuhuPB5ePARIMOLKaAE8RqbmSESJyaluMTwA9MU84mhwyZosSeJaOnriFGgoceg8uGgVRRzeFQRFPrR5KWj8RbFERhAotADkPgD6PqTkVDS0Ptv88xPuU2gkyriGSqrqmrRgNBTOrgexJcWAm36Av4qADqaA37aABUqAFzaAKcTAG+mgBh-wAA6YA-I0AbE6Acr9Co9YgA3Ej1KAotAQbyBG5oChENEVTG0YB8FhQNCYHjzACiAA8oAMCJcAMpwai4jFweY8AC++0mTwJnKIACM0E06AADUo8QEARgVPHoMR8wCFmLCGO67No-B5ys0MsBgGW-QD65gqFQbJfyETx1XBReKJHR5kaAYAAfUA05pKtx7UjyGjiBYGt1mvbwp5PAWxAbpe1EcRIJBwXWaiDazb7SN8gUJpMprNPNMZug2mOVarlNCDCD6iBCcDQeAAGTIoTkrHJBGU4jA9gbuBIBAAChU4Gpulh5CQ2AQ0MICDARQA1MBoEQAFTJGGwcAqGB5QA)
