### ISSUE TITLE
请问selector如何匹配不等于

### ISSUE THREAD

**Issue by littleinsz** [thx/gogocode#11]
打个比方：
import A from 'a';
import B from 'b';
import C from 'c';
想替换from后面不等于‘a'的import代码，类似与
“import $_$ from '[!a]'"这个意思
请问一下选择器要怎么写？谢谢

**Comment by shuerguo999** [comment]
`
$(`import A from 'a';
      import B from 'b';
      import C from 'c';`)
          .find(`import $_$1 from '$_$2'`)
          .each(item => {
              if (item.match[2][0].value != 'a') {
                  return;
              }
          })
`
建议这样写，逻辑复杂度没有增加，可读性较好
是考虑到选择器尽可能的贴近原有代码结构，才能更容易理解和使用
