### ISSUE TITLE
无法解析js文件中vite暴露的环境变量 import.meta.env

### ISSUE THREAD

**Issue by keyingfu0** [thx/gogocode#111]
- version: 1.0.40
- playground demo: [link](https://play.gogocode.io/?v=1.0.40#code/N4IglgdgDgrgLgYQPYBMCmIBcIBmMIDGcYSEABAOZpwCCARgM5IA28aAqgE7MAUM3ASjLAAOuTISCpJszQA6Zkgp9BYiWBxkeAQn7Mhnav3IByE2rKG4xiQAMAJMDABbKEk5w5z6gEM5aCAA3OQA1AEkAFQBRAH0aAAV4mIAhGgBlWPYAJQAZAF8Aekc9PNsxPJAAGhAAd3cAa2R0LFx8IhJyOE4fCAYcd2ceHDBZMIh+yrIfKDBJpChiaSFRcSleuDJ7MgBeKZm5CiUkKXQLNYYNpn4CNB2yYdHxpDkrzhuLAoLLI05yAE8kPwyF0en0BmgUGQTrcABZoQwWKw2ew8V43AQWCRyQxQZg+G48EznFjyRTKAQmSZmDHiLFUCDwnxwNA8Gl5MSYshVcDQeA5HoUFpwP5QNAMAicMALbkwnwMeJWYjwrBdGBoaoMGB0EJgNA1CIijDYKSuHyGEB5IA)
- detail desc:
当在 js 或 vue script 文件中使用了 vite暴露的环境变量 import.meta.env.xxx 时, 无法解析

相关文档: [环境变量和模式 | Vite 官方中文文档](https://cn.vitejs.dev/guide/env-and-mode.html)

**Comment by senyawang** [comment]
底层 babel/parse  需要设置  sourceType: 'module'    才可以识别 ECMAScript Module grammar

![image](https://user-images.githubusercontent.com/2443802/149087628-24f89266-58bf-43ca-93e2-a56b2d421abd.png)

**Comment by shuerguo999** [comment]
parseOptions里传入sourceType: 'module' 即可
https://play.gogocode.io/?v=1.0.40#code/N4IglgdgDgrgLgYQPYBMCmIBcIBmMIDGcYSEABAOZpwCCARgM5IA28aAqgE7MAUM3ASjLAAOuTISCpJszQA6Zkgp9BYiWBxkeAQn7Mhnav3IByE2rKG4xiQAMAJMDABbKEk5w5z6gEM5aCAA3OQA1AEkAFQBRAH0aAAV4mIAhGgBlWPYAJQAZAF8Aekc9PNsxPJAAGhAAd3cAa2R0LFx8IhJyOE4fCAYcd2ceHDBZMIh+yrIfKDBJpChiaSFRcSleuDJ7MgBeKZm5CiUkKXQLNYYNpn4CNB2yYdHxpDkrzhuLAoLLI05yAE8kPwyF0en0BmgUGQTrcABZoQwWKw2ew8V43SbAMhQHycBhoADyCw6DEwwjRaAifygaFJJmcqBgshMeTIeQEFgkckMUGYPhuPBM5xY8kUygEJkmZnZ4k5VAg8J8cDQPGleTEHLIVXA0HgOR6FBacCpaAYBE4YAWWphPgY8SsxHhWC6MDQ1QYMDoITAaBqlOpLSkrhxGDyQA
