### ISSUE TITLE
如何 插入 import 语句

### ISSUE THREAD

**Issue by lyuehh** [thx/gogocode#113]
我的需求是
```
import { A, B, C } from  'aa';

function aa() {
  return <A />
}
```
替换为
```
import { A2 } from  'aa2';
import { B, C } from  'aa';

function aa() {
  return <A2 />
}
```
把部分组件从新库里导入，旧的不变，需要支持插入新的 import 语句，并且 删除旧库的 组件，请教下怎么做，试了几种方法，没法 插入和删除

**Comment by lyuehh** [comment]
替换A 已经可以了，保留 B，C 还不行

<https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBc4C2UkBOcABMMQIIA0xAQtQsQL7EBmBSOxxA5AIa-cA3AB0IoljAgBjOGCQRi-ABQBKUqK4E0cGAQUAecsQD0APlGMQlEAHdCAa2TosICdNnzicArwgBnFkIcJRYwABs0AEkIQOpeKDBqJCgPfzVgDWIpeT8SABJiAF5FBIA6AHMkSuz0TOz-Ej8kXSk0ItZwqJikUqaWtFFMgDdeAmIcePaMhS4KTB5yACZuSkzGQZn63OI0AA8wXL9yAjHigHkAIwArNBlS+zQATz8lCagVOpySMLALgEZ2nwBJ8GsQfhdFoD+MsNlwIiR2EgSMU8ko+gRWh8ZlxSqEICglAADMB4QgkMh5AD6eQBzDYHB4VLyy0EhKxs2IpTQvCkAAslEowHA0Dg1IVTOpsbMtkgIqUwlUlNwALSq4i5UYkVXcdkcrI5WVoeWKoUi3Uc4zGGVyhXlJQAKQAymcAHK9byQcpgFiPQXCnCUCAwMJhSiLFTm2aW4haKBhHltEn4IisdicXxwFBeJDEFBQDGZC1Wg02k3+0oTOB8yNcS0AbW4NBo3AAuoXZt7iH6RRXeFXeXXFi26wAGFulEZhGBtQqzsG-P7pdsckZjKS6LQQZHEU04Xv9ut-cdvAW7MUS3YT3hTtA12ar4iSMAARwQG7QW-addKP4gaBsxCOtoSjricH5wCobZSiuow7kcIYAKL7NsxRPq+75blyQxoAQvpKGeRTmNBep7AccBHCcpSQFIU7oC8Z7LrMd5cJ2grwWESFkUuxFFsQgBBmoAOeaAL8JgAa2oAFOqADD-gAvboApcaAP9mgBGxoxHK7vufKDsOY6lBAqBGpO07tOCizKR25aVupR64oQCE8vyrx9tWhGSnqLnjA5vLabp2m8DgM5uVAdbmR5+loFBrmzIwzFMDsYR+G00zhbWxjEIAZCqAJhKEmAFfKiniYAIW4SYAmq6ANBygCwcnlJlcA+pGHO0aFvmBmGhGEwoEKe54VbM1XkccBBUdItFoPRUVcMNJjJYJgAXCYAYEqACN+gBvcoA98qKYAXHKAA2m80daxXV+PKH7lHAvLEBKI7cYlszwjupJEC6untKpOm1DxeoXbwALFEmZI3egvRQLc3pgDhO1NS1bVOQlZ2zFoOh6DsyHdZR1EDfRVFXcKKDeb5o1cJFHVwtoiiQu9qNfUafi-VI-2A7i4Qg-h57ORDmjaLoCgAITbT1fU0TAdH4SjyZoxjt640wWOKH8VkEDZfKg+KDOM5eH1EGg6MQD5flvHWiuoyrQthRDONPSpxNeWTf2hID7SvSLStwCTvTNBienXgZxRGR16xPZ7Lne3q1pGraSqqsqOz4sQ2qRobHKlIicCqLCxCXDcdwPM89nvJL0t2QRcvg5oSBIjHaBxgm+HUJruwtrqUcxszMOxxUH44X2aDxxAntWOA0DwAAMr45QuHAjy-X4UgEGAKSd7yvB+AAClDsg4VgLDXnF1h+DAFwAGoAzYAAqw8YNg3hoBgjBAA>

**Comment by zhangdaren** [comment]
item.after("import { A, B, C } from  'aa'")   
在import下方插入代码。其他逻辑你加一下呗？.

https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBc4C2UkBOcABMMQIIA0xAQtQsQL7EBmBSOxxA5AIa-cA3AB0IoljAgBjOGCQRi-ABQBKUqK4E0cGAQUAecsQD0APlGMQlEAHdCAa2TosICdNnzicArwgBnFkIcJRYwABs0AEkIQOpeKDBqJCgPfzVgDWIpeT8SABJiAF5FBIA6AHMkSuz0TOz-Ej8kXSk0ItZwqJikUqaWtFFMgDdeAmIcePaMhS4KTB5yACZuSkzGQZn63OI0AA8wXL9yAjHigHkAIwArNBlS+zQATz8lCagVOpySMLALgEZ2nwBJ8GsQfhdFoD+MsNlwIiR2EgSMU8ko+gRWh8ZlxSqEICglAADMB4QgkMh5AD6eQBzDYHB4VLyy0EhKxs2IpTQvCkAAslEowHA0Dg1IVTOpsbMtkgIqUwlUlNwALSq4i5UYkVXcdkcrI5WVoeWKoUi3Uc4zGGVyhXlJQAKQAymcAHK9byQcpgFiPQXCnCUCAwMJhSiLFTm2aW4haKBhHltEn4IisdicXxwFBeJDEFBQDGZC1Wg02k3+0oTOB8yNcS0AbW4NBo3AAuoXZt7iH6RRXeFXeXXFi26wAGFulEZhGBtQqzsG-P7pdsckZjKS6LQQZHEU04Xv9ut-cdvAW7MUS3YT3hTtA12ar4iSMAARwQG7QW-addKP4gaBsxCOtoSjricH5wCobZSiuow7kcIYAKL7NsxRPq+75blyQxoAQvpKGeRTmNBep7AccBHCcpSQFIU7oC8Z7LrMd5cJ2grwWESFkUuxFFsQgBBmoAOeaAL8JgAa2oAFOqADD-gAvboApcaAP9mgBGxoxHK7vufKDsOY6lBAqBGpO07tOCizKR25aVupR64oQCE8vyrx9tWhGSnqLnjA5vLabp2m8DgM5uVAdbmR5+loFBrmzIwzFMDsYR+G00zhbWxjEIAZCqAJhKEmAFfKiniYAIW4SYAmq6ANBygCwcnlJlcA+pGHO0aFvmBmGhGEwoEKe54VbM1XkccBBUdItFoPRUVcMNJjJYJgAXCYAYEqACN+gBvcoA98qKYAXHKAA2m80daxXV+PKH7lHAvLEBKI7cYlszwjupJEC6untKpOm1DxeoXbwALFEmZI3egvRQLc3pgDhO1NS1bVOQlZ2zFoOh6DsyHdZR1EDfRVFXcKKDeb5o1cJFHVwtoiiQu9qNfUafi-VI-2A7i4Qg-h57ORDmjaLoCgAITbT1fU0TAdH4SjyZoxjt640wWOKH8VkEDZfKg+KDOM5eH1EGg6MQD5flvHWiuoyrQthRDONPSpxNeWTf2hID7SvSLStwCTvTNBienXgZxRGR16xPZ7Lne3q1pGraSqqsqOz4sQ2pYoxlqAEvGgCmioxqm8CwIPCLgAukBQ1B0MQDB0mmXBAtwqeRobHKlIicCqLCxCXDcdwPM89nvJL0t2QRcvg5oSBIuXaBxgm+HUJruwtrqpcxszMMVxUH44X2aBVxAntWOA0DwAAMr45QuHAjy-X4UgEGAKQr7yvB+AAClDsg4VgLDXnF1h+DAFwAGoAzYAAqe8YNg3hoBgRgQA
