### ISSUE TITLE
clone 没生效

### ISSUE THREAD

**Issue by chenjigeng** [thx/gogocode#120]
- version: 1.0.41
- playground demo: https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIDGSIDOcABAIbEC8xwAOhMWQOZqbEBMbANHQwUgLYtiAcgBmSJMLoBfEJxAB3JACcA1snRYQomBBxww+YnGWlC45fwAUosABs0ASQjjOZKGDdIoB-AQCU1DzEeIQkACSU7mAAdIxI8XjowaFExHwwyjhoUbYOzuIxGVlowQD0ZcTKaHCZ9ACeSJnGpuYqgighqDkAFmjVKX4kpGlU4VbF2f6DYcQQaAoAgqNkRDE4dvhoVtP0VTV1cwvLcDG2EChWwqnDUcDE4Y-E0sL+cWjzpnDbu9J0cuBoPAADJmRhaOD1KBoAg4ZRgHwAnojAAK1TgBn6WFEpDsBDQ8gIMAARgA1MALAAqUIw2BMaAw0iAA
- your description:
正如 demo 演示的， clone 后先调用 find 函数，之后直接调用 generate 会返回空值

**Comment by zhangdaren** [comment]
v1.41，clone后generate()报错：
``` js
/**
Something goes wrong...
TypeError: t.skipSpaces is not a function
**/
```

但v1.40里clone后可以generate()的，但clone后找不到了，找a也找不到

**Comment by shuerguo999** [comment]
v1.0.41 fix
