### ISSUE TITLE
获取属性列表后 通过attrList.push 新增属性时，属性值没有引号包裹，且缺少空格

### ISSUE THREAD

**Issue by senyawang** [thx/gogocode#125]
- version: 1.0.45
- playground demo: [link](https://play.gogocode.io/?v=1.0.45#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8c0C2UANgIb4B8AOhAAS04pgButzAtMUqUxAOYBeKiC49IfYbQDGZAM6yhIWQAseSAO6c+tAE5IYEdCnYEUtJMzQ6AZl03KwKdBGHU69BmGs7SBNDQ8PHTRrRS8fP2EAwOk5BWFw3zR2ACMkAA8o90DvJLSddB1FAAYsmNpMWR0pRRgdYjKYgAFRFEVW8VoBWmtSYll-EGj6AHo3QJwAQnZ2Bj14K3ZmMDR1NnY0frQKHBH5-B0llfUKWhnxhhGmZjdd-CIyShoaHFkpHTAoODcwIiQdOC0YC0AikKAAcTQcAOsloAF8enoCLQAOTMGBodIomiYqD-QHoXowYiA4DRFDkUgACgAlEDhrooXU6GTsh46sRMKiUQAaBn0Dr8Lm9LZ8tlw6JwsX0KRIIgLFBc1mBAB0atBEKhMKpAG0UVI6sEIHAAEr6fAogC6NOl8Nt6nIUmUSoZBp0RtN5rQLrZ9FUhmIVipzD6PPMxBQADU+nTleVaF5aMG+rQAGSptgpyYCbpICPR4ix-kxOAOWQqwXabpwHQY4uBUtgcscrq0AAGABJgL88QCVX44KQVWgIMwVZGAJIAFQAogB9AASAHkAMpTgByAEEALIzuFdkPEFVQcjKOFt+vw4tS4u-PxMcje2g1jG2+g39wfiUQXZvD5fNwXlkOAAE9AzcFVEj8VIMnpdx1EcUsuQARmKYoAFIAG5omUNAwD4ZQ4C5KQ+ikKlUOKZhlDOWgAFYADYoHSGlsIgb9f1A8CaBAHkQHUf4AGtkHQLAQGsAwpDgMAkDoGtSAgWRrH+AgqWsMBAwnCAlLDMEwDDJAvmkhSi3cWUFMBDtW10lU+CQWzZXQaIzOA2hZH0ao0FbNSNK0pAVTcuopH8OhnNJWgoD0KBZB06EdAAaTQED4VbAypJk2EAB8MqBb9i1C580GAhKku6cga2K2gstRClB3YUh4DlcgjOxFxfVoQNAQgVYV3coLWwCjzhmGfLFKkTcXO6DsqS69QesCtAwzjcoTx0AYl0M9KfXjDwyH4GBSD4J80QxXlL3oAagqnECoCOghUGJNBTra99rxpZ42vyiKDNkTcdBK2gdUvFFgmsXlUQ4O70GIMGUS+qAYY4WQuDgGGkaQFGwxRJoZDAKQBJh7H-UOgmcbx-y4AMp7tqx0mBOPYJLGNEniFxungIM+m0EZjHUWxlmyZPeQWEezGICSGGyBSTYYcwQ8TsxmRgIOqmYktd7ykTKk4dhdNwsi8tA34UsTO27XfpA-ySFxtAqXYAAmMNijDNV6e+t62tytqRhGWhAAlFQAsBMAcfjAD0dQByA0AU-NAD8jQB-s0AI2NABh-wBYxSjwB1bUAMm9ACY5QBCK0Af3M8vSwF7hIR9xsBbpRtLy8VTUwwqRRPBCGLyg7kbx5thRd3turyAUDrnAOznDtkNoAeOztxRR4AZkkDtZ9oCgO6rtBSCdKkqTAe46QEU4lvjfKyp0AAZJsy4Te4VQPuuzPwY0L9isAUgWWRF+enaoVoA-tzBVtgG-bb6APsfYC1d-gzhXsoNeB8t47zOh4A+Ko5aeV1lST+YIdTwIEolFU18RxwEtFZWKCC+gYmwTJG+cBO7-zhJQ7a3taCAEhjQAXhmAHi9QAGPK+0AOV+gB24MAGvKgAgoMAJ0OYdAA8CrAjqtAZoFgxAQmsX8oA6jNn9butcN6EC6KcVB8jVEEHwTSNWrV-60DoYHQAJ3aEA3oAaLlABvcoAWBVYH5XMaaNAVYjFUCoB2RxbjdRuOfsIS0ABqHxAAqbxVBNBzgCTSEYsDNaOJNM4lU+BgLTVWFItANI6SSOIZ5boWTiAkNBHAVecTnE0h1MhfR9iC6ZnyWgeJLiRgAD03HqH8TqdgKo5wtMtEElp-iqReJVL0qgGSAD8HYfZGJ9oASHNAASpqIgx-86GABIlQAtaaAA1tQAFOqAE8nQAWdph3joAFDkRGAAgVQAqzYxOsEmPJ0jdaIPqYkwqcAUnqDSRkuChiAGxSAXAY8MAVBUl3oYzBIEtqfIbNdI6FNMEQEwAfB+Cx2AgpVuCmUZDcFciSXAYqb5PkflRTUjEYKCWgRulyFE0KRxwvvo-fASxskotRTg40XIbkLVgYEfFeKaHxj-rynlqo9Do1pFXGuvd65FzbjsEYkrHwLwFR4OhqdM651FT3OuwBgAvy7svVe+B0hwFLuoj5-9Nb6sNcAiAqA0CkONLgohtTbXkP7I6CBKI4Rwg7iZDlCYrlUkmOa0ux5SAelpHfGsV90W33hbSwqXqCoGqDStXBYbL76ijb8mNT8wY6mtOrT5KzVmAFBlQA1CqavhHywx+9vkn1bIG4BybjSptipGu10aaXZrpFVXNPrxGaJ-pW-+gCT4gJ0GA1eKDYrQJNeC+BiC0wZknbItBGCsHMrwTInQDqSHroVeUahPr8qFKdGgMw1ZMQWt+Va9ATr7WINvbfY9ECRiasBlQWQbiVw9LhCMPdMR8pstbE+09Opij4N1sBlAoHLQuqKc+lpOoVRuPYF0sJATf0LpBK6kDYHYOr2iWExDyHUPqDfZadDZSwM+roc5PMNquB8BeWk0WqxDwiw-jW4Cf7Aia0mJonUWLirgYzGyk2qLh0Nv+RAoFnyQXEoJc+SF5LKWwqzXS5FuKCXrsxU8nFPrOWac+Yg+TJKlOohU9SmsCK6WIMZVpjNrLUnZMM4Yrl4KD2v05bAwdnK-0qiFc8vzYq+5-k+N8X87wwvysvHQwAIJqADAXI0hRAC-ioAB1NAC0coAELcABWshMiv2UeKpLQYaS-21fGQrfdR7DxkggfmAkJ6D2niACgs8Oy7Gq9FgruqIHr03samTgRq01h+a2bR26bUGRHOIGcgY-Dtqs7Gj9nn2rv37d0X+sCJO-KUmO8BkCp0DZ9XO7JmGl06DkegwhYs-Aqhu2gfBpVCH3sQdx+Eb24vxZkrTQAXOqAHszKp5lCU5I48u+RKJav1atJVbK42n06knpaaDE3AcuRmgAMXUgcNJrZ73BGLkFKkBGADqIw+CYw7v5tABObYjCpI2WQGVHEZRSD3KJ5PuRvYA052puPsl4efQztxSGwn+Iw6M4HAuidC6oCL1pv7oMVAkasTHJIrBpPzdtcb96psQBm3N+1anCp-IBYNksZmUQACkVwAA1NwdotC5mI92TP-1JUda3NuJzOCkmpKwdn-4u4KkVRKTuDM+uMzOz57vyUris-wY+Bw+gB+2pHtlYePBuf5ZeDz5QZpzQ8nW1uJdgJVwCyKgrh0uo+HwBXy8wQ4DMmV7NXqwVvw8XANAeAh95J8FEuiDAvFVCyAAAoN6klYLAIoBi8VkDAFIkZjhXRuqJWURAQ0YDhEAA)
- detail desc:

通过gogocode 转换后的自闭合组件，我通过attrlist.push() 新增属性后， 最后一个属性与闭合 / 之间少了个空格，比如： <component  property=value/>  ，而且 value 没有 “”， 这就导致 vite-plugin-vue2 识别错误，报错，  把push  换成  unshift 可以解决这个问题

**Comment by bigfengyu** [comment]
我观察你这里的 value 是 iframe 没有加上引号，这样本身就会带来问题的。如果你在构造节点的时候给 content 加上单引号，生成的就会是正确的结果了。
