### ISSUE TITLE
:visible.sync转换失败

### ISSUE THREAD

**Issue by unbregg** [thx/gogocode#130]
- version: 0.2.25
- playground demo:
- your description: 使用 gogocode-plugin-vue 将vue2转换成vue3遇到如下问题：
源码：
`<Modal :visible.sync="visible" />`
结果：
`<Modal v-model:value:visible="visible" />`
期望：
`<Modal v-model:visible="visible" />`

**Comment by shuerguo999** [comment]
已修复，重新运行命令即可
