### ISSUE TITLE
想往数组里加多一项，发现数组内其他项的逗号都没了

### ISSUE THREAD

**Issue by chenjigeng** [thx/gogocode#131]
- version:1.0.48
- playground demo: https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIC2qYA2aAdGgB5RIBOcAzgAQC89wAOhPfbWlQG5gBjNLUz0A2u06c2HKXIgBDHGlEAmADSSpAX02zpWuZ0XK1eubvZaAunu0BudiHUgA7tQDWydFhAAzGAgBODAkDjgqBQhaP2ocAAo-MCIASQhY9XoFKDBMpCgQsNoAShYtASK4egASJiyc4gBzJGaK9HLKriQYKiE6pNT0pGJabt60K1kqNDgejmr40Z6hYsN6YmmoAgUheIBybj5BYVExavOARms9zIOefiERcXPqq73V-XXGtAgeBTg0PEPtonC5ILA4AAZKKNXxwACeUGEAioYAKzhAAAsFLQAArTOAhHhYCIwNAuWgwABGADUwGhXAAVREYbARNAYbRAA
- your description:
想往数组里加多一项，发现数组内其他项的逗号都没了

**Comment by kltk** [comment]
翻了下文档，通配符是 `$_$`，没找到 `$$$`，测试正常
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIC2qYA2aAdGgB5RIBOcAzgAQC89wAOhPfbWlQG5gBjNLUz0A2u06c2HKXIgBDHGlEAmADSSpAX02zpWuZ0XK1eubvZaAunu0BudiHUgA7tQDWydFhAAzGAgBODAkDjgqBQhaP2ocAAo-MCIASQhY9XoFKDBMpCgQsNoAShYtASK4egASJiyc4gBzJGaK9HLKriQYKiE6pNT0pGJabt60K1kqNDgejmr40Z6hYsN6YmmoAgUheIBybj5BYVExaoB9aoBGaz3Mg55+IRFxC+vb1f11xrQIHgU4Gh4p9tE4XJBYHAADJRRq+OAATygwgEVDABWcIAAFgpaAAFaZwEI8LARGBoFy0GAAIwAamA0K4ACpIjDYCJoDDaIA

**Comment by chenjigeng** [comment]
> 翻了下文档，通配符是 `$_$`，没找到 `$$$`，测试正常 https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIC2qYA2aAdGgB5RIBOcAzgAQC89wAOhPfbWlQG5gBjNLUz0A2u06c2HKXIgBDHGlEAmADSSpAX02zpWuZ0XK1eubvZaAunu0BudiHUgA7tQDWydFhAAzGAgBODAkDjgqBQhaP2ocAAo-MCIASQhY9XoFKDBMpCgQsNoAShYtASK4egASJiyc4gBzJGaK9HLKriQYKiE6pNT0pGJabt60K1kqNDgejmr40Z6hYsN6YmmoAgUheIBybj5BYVExaoB9aoBGaz3Mg55+IRFxC+vb1f11xrQIHgU4Gh4p9tE4XJBYHAADJRRq+OAATygwgEVDABWcIAAFgpaAAFaZwEI8LARGBoFy0GAAIwAamA0K4ACpIjDYCJoDDaIA

谢谢老哥，亲测有效
