### ISSUE TITLE
v-if 上中的 key 属性会丢失

### ISSUE THREAD

**Issue by unbregg** [thx/gogocode#135]
- version: 0.2.23
- playground demo:
- your description: 使用Vue2转换Vue3的工具，key会丢失
- 在有些使用了 v-if 的情况下，还是需要保留key的，例如路由的keep-alive，如下述代码，key是不能丢的。
```html
<router-view v-slot="{ Component }">
  <keep-alive>
     <component :is="Component" v-if="computedKeepAlive" :key="$route.fullPath" />
  </keep-alive>
  <component :is="Component" v-if="!computedKeepAlive" :key="$route.fullPath" />
</router-view>`
```

**Comment by unbregg** [comment]
这个问题有计划修复吗？
或者有什么办法能忽略指定的几行代码

**Comment by eyis** [comment]
考虑 Vue 3 也兼容 v-if 的 key，为防止这个丢失参数的问题，插件决定不处理 v-if 上的 key 了
下个版本修复，感谢支持

**Comment by unbregg** [comment]
@eyis 多谢～
