### ISSUE TITLE
bug：无法使用通配符去匹配标签上属性的值

### ISSUE THREAD

**Issue by FliPPeDround** [thx/gogocode#139]
- version: 1.0.51
- playground demo: https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8A1MNAdwD4AdCAAkv0KMogEMBbNAXjJAEZPKBjADaMAzsI4hGfOGABuaXgHpyVGgWIMW7TjxCUwKcQGs0AT04k4aAB5wcCtaQp2HJEABoQRJACdDydFggAGYwEFJgSFRw3owQwkE+zAAUQWACaACSEAlulIxQYLlIUNKRwgCUlMAU1HxlcJQAJJRseQUAdADmSN116DX89ZTCSDDefGgtlKnpWQntI2MTAwoKlN5ocGNUJqPelNGx8YloKIPolAAWaBsDdXENG8IwAg2tjUmL42jl7RtQQgmSQG1AABrR1ExWOJGrCAMy8WGNLgkJEAJmcdBIoLcIMo4IcBxMUC0ICRCN0SJR6MxxGxA3KAw2W28VCeLzgXTQEBujEsSUZEAAvhR3OBoPAADKxTqBODEtDCPjeMAlMWXEQABWZ0huWCCjAEwjQHmeACMHAAVBWBOrMKCMDYgIVAA
- your description:
无法使用通配符去匹配标签上属性的值
![image](https://user-images.githubusercontent.com/70848683/159399936-a1a8db39-464e-494e-b545-fca80bc69f96.png)

**Comment by shuerguo999** [comment]
$$$这种通配符用于匹配多代码节点，$_$用于匹配单代码节点，[详细说明](https://gogocode.io/zh/docs/specification/basic#%E5%8C%B9%E9%85%8D%E5%A4%9A%E4%B8%AA%E5%90%8C%E7%B1%BB%E8%8A%82%E7%82%B9)

https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8A1MNAdwD4AdCAAkv0KMogEMBbNAXjJAEZPKBjADaMAzsI4hGfOGABuaXgHpyVGgWIMW7TjxCUwKcQGs0AT04k4aAB5wcCtaQp2HJEABoQRJACdDydFggAGYwEFJgSFRw3owQwkE+zAAUQWACaACSEAlulIxQYLlIUNKRwgCUlMAU1HxlcJQAJJRseQUAdADmSN116DX89ZTCSDDefGgtlKnpWQntI2MTAwoKlN5ocGNUJqPelNGx8YloKIPolAAWaBsDdXENG8IwAg2tjUmL42jl7RtQQgmSQG1AABrR1ExWOJGgB9RoAZl4jRRXBIKMaACZnHQSKC3CDKOCHAcTFAtCA4Yjkaj0SjsfZcaCBuUBhstt4qE8XnAumgIDdGJYkqyIABfCjucDQeAAGVinUCcDJaGEfG8YBKUsuIgACuzpDcsEFGAJhGgPM8AEYOAAqKsCdWYUEYGxAYqAA

**Comment by FliPPeDround** [comment]
不好意思，上面那个例子可能不恰当，在属性复杂的情况，使用$_$同样有这个问题
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8c0C2UANgIb4B8AOhAAS04pgButAxmQM6cC8VIpfrWYBaMADM+IACwNagkBQCMOAPRNm1Ogw3suvfgooAmNRq1r8RMpRo0cnNgCcwUOFrZIInOPNo9aJRpPb18AI39aY3tVRxc3LRAAGhAAdyQnAGtkdCwQcRgINjgwL1o4J1JvcQyCAApxMGI0AEkIGqT5KDBOpDdS7wBKWmAaehCfWgASSNJugDoAcyRlz3Qx9i9JziQYJzY0SMbmtpr5nb2DjYnfUkmAqbqL-bRO4FooUidONAB5fq2mBGtDIEEWMFIizQQIA5MwYGgYbQAL4owbXLa+KwkciHAJ3ODzRoQFB1GF4Qg4yiWSk2NAUGHo7Q3WhxVy+fE+ImQUnktkJNT89yMuzabF0+ZONA4g51Db0cm6UQSKRTAD6UyUcnVU2iIGmU01FB1AGYzCwGUl5bRFSxhGJJPwdVqKNMNXqDUbTebNDCNkz6ELJdKyLKYSzSJEdTDOuHMX4AsZGUs0BA0JV8HUA7RVKpaFK4Hs6ABPXZOcqVaq1NAoTboWgAC3TaA2BaL8i5ULTGbQWZoyJoyXA0HgABkqos8vCMCkG3cAAoFkrprDiUjEH4pTgwMIANTAaFSABVi1AMNhPEQvhhkUA

![image](https://user-images.githubusercontent.com/70848683/159423844-0a6933c4-a50c-4281-b976-201567a8b0f3.png)

**Comment by shuerguo999** [comment]
对于html的属性只能作为整体用单通配符匹配，针对这个场景可以这样实现：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8c0C2UANgIb4B8AOhAAS04pgButAxmQM6cC8VIpfrWYBaMADM+IACwNagkBQCMOAPRNm1Ogw3suvfgooAmNRq1r8RMpRo0cnNgCcwUOFrZIInOPNo9aJRpPb18AI39aY3tVRxc3LRAAGhAAdyQnAGtkdCwQcRgINjgwL1o4J1JvcQyCAApxMGI0AEkIGqT5KDBOpDdS7wBKWmAaehCfWgASSNJugDoAcyRlz3Qx9i9JziQYJzY0SMbmtpr5nb2DjYnfUkmAqbqL-bRO4FooUidONAB5fq2mBGtDIEEWMFIizQQIA5MwYGgYbQAL4owbXLa+KwkciHAJ3ODzRoQFB1GF4Qg4yiWSk2NAUGHo7Q3WhxVy+fE+ImQUnktkJNT89yMuzabF07kkuobejk3SiCRSKYAfSmQRA0ymaooKqmAGYzCwGRsmfR5mhSGwABZ1MBWfwUEYyzbeJDNebEFa2qzzAjka0AbSUAF0AwAGYOm+i0O2EX3+q1B0MR+YQVBoeYhfAQDkxn1+uCBkPh4Op9OZrzZwlONA4g5knAwzowhlR5FR+ZOJBIOB1KNCpZoCBoSr4PsbVSqWg1uB7OgAT12TnKlWqtTQKE26FoVpHaA2M7n8i5UOHo7Q44gyJoyXA0HgABkqos8vCMCkrXcAAozkojrDiKQxA-CknAwGEABqYBoKkAAq85QBg2CeEQXwYMiQA
