### ISSUE TITLE
无法正确识别解析 vite插件的热跟新模块代码

### ISSUE THREAD

**Issue by FliPPeDround** [thx/gogocode#140]
- version:1.0.51
- playground [重现地址:](https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcID6BnAMwGMcBbAQ0gDoccALUgJwEkUACAXjYB0QB2AEbkArAJQBOAAy9uEOAE8oaJATa0AagFUAojgASAWQBKOI5oByAFWYHdONgEIOXAOQwI6ApDQoXbAGT+ajhauoYmZlY2dlREjGjkcGhGaERIjCgAFPjEZJQQNPRMrAA0aoQkFJAAlLKyAPT1bICb8YBUcmCkUOlwgJzKgLKJgIyagKSxsh1djHBUpGhw5FR0SJPkRERoUHCZmcBsnuQwADZwmGwwUCiJPmU48fEeaIw4SBD78mwAvtWcAHxswLJsbDAqmyNzQdweTxenz+EABAI0On0xlMFmstloVFB4Myp3OSRQhQYLBQZVxFwJt3QjFqsPebDQ+zwaF+-zhCLCyMiaJi8X2SHIWTJ+MJxRJJzO5JpALesg+DSabTG3X6wzqECVEzUaAAHuM4DkiGwCIwkKQ2C4oPsYABzSAAWgAbjA0JgdXq7XQGUpGC5ZG7ujs0AQ9oc2PUAFQAYloAAVNEY7OH6jh-RMDdkKnlIGUANo5lyU+4uEoG65gqkAXRK+doXn2aGLvAQmHqmiZjDw9QAVkge4owdb6gARNB4ADWcCQUHqDrASTtlpt9rgnog9TwjCI9QAglAoFQnWheBWK9UQCUQAB3dJj5DoLAgAjuIhwMBPNhwRjkCCEdKkTJ1mgzAQAQSBlOQUBgGUU6vk8eDQqyaQ-nAbAACScGwEFgFQ1pILhaToIhcEoXgSAwJuzJcIBwGgVQpHkasrKNGw8RwORsLyGRjAfl+P6gYw0zsARzKevErKsexaGZPRFFSnCmJrPsyxoJkLillUBS0ESrAYahOCocW5rqfkIrEhhACMLhyQCOFgvcFyZDSMoQOe4DQPAAAy37Wg+ChKHgcRgOsrl0OQeAxqxr73FgwaMmgF54DAAjqGAaCXpY-a+fEGBvEAA)
- your description: 我在使用gogocode开发vite插件的时候，如果拿到的code是被之前的plugin处理并加上热更新代码后，vite的热更新代码块会使gogocode编译失败

**Comment by shuerguo999** [comment]
import.meta 需要在parseOptions里增加配置
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcID6BnAMwGMcBbAQ0gDoccALUgJwEkUACAXjYB0QB2AEbkArAJQBOAAy9uEOAE8oaJATa0AagFUAojgASAWQBKOI5oByAFWYHdONgEIOXAOQwI6ApDQoXbAGT+ajhauoYmZlY2dlREjGjkcGhGaERIjCgAFPjEZJQQNPRMrAA0aoQkFJAAlLKyAPT1bICb8YBUcmCkUOlwgJzKgLKJgIyagKSxsh1djHBUpGhw5FR0SJPkRERoUHCZmcBsnuQwADZwmGwwUCiJPmU48fEeaIw4SBD78mwAvtWcAHxswLJsbDAqmyNzQdweTxenz+EABAI0On0xlMFmstloVFB4Myp3OSRQhQYLBQZVxFwJt3QjFqsPebDQ+zwaF+-zhCLCyMiaJi8X2SHIWTJ+MJxRJJzO5JpALesg+DSabTG3X6wzqECVEzUaAAHuM4DkiGwCIwkKQ2C4oPsYABzSAAWgAbjA0JgdXq7XQGUpGC5ZG7ujs0AQ9oc2PUAFQAYloAAVNEY7OH6jh-RMDdkKnlIGUANo5lyU+4uEoG65gqkAXRK+doXn2aGLvAQmHqmiZjDw9QAVkge4owdb6gARNB4ADWcCQUHqDrASTtlpt9rgnog9TwjCI9QAglAoFQnWheBWK9UQCUQAB3dJj5DoLAgAjuIhwMBPNhwRjkCCEdKkTJ1mgzAQAQSBlOQUBgGUU6vk8eDQqyaQ-nAbAACScGwEFgFQ1pILhaToIhcEoXgSAwJuzJcIBwGgVQpHkasrKNGw8RwORsLyGRjAfl+P6gYw0zsARzKevErKsexaGZPRFFlNsUDkB2aAAPLrG+P7HNsMmrJY-bHC4pCoAcDbvHKtIApiaz7MsaCZC4pZVAUtBEqwGGoTgqHFuaDn5CKxIYQAjC4UpwjhYL3BcmQ0jKEDnuA0DwAAMt+1oPgoSh4HEYDrHFdDkHgMasa+9xYMGjJoBeeAwAI6hgGgl66UoaXxBgbxAA
