### ISSUE TITLE
模板字符串匹配内部表达式失败

### ISSUE THREAD

**Issue by yaruiyang** [thx/gogocode#141]
version: 1.0.51
playground demo: [链接](https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIAGh36MGT4wU0VA2NMFbrAEmEnQA8ACAanoEYBfcwWBVAHzxxABoQAdyQAnANbJ0WEADMYEAMZwwSCPTiiAhhADOssQFsAFLLAAbNAEkIB-vS1Qw9pFBVrdASnrAAOuvpFDzh6CnoAXgcnADoAcyR4oPR-ekDg+l0kGFFFNAj6M0sbA2jM7NyU+gB6KvpRNDhs9QBPLNENbT0DUUM0FDT0egALNHrKoL0Q+t0YcxDIgG0AXUqKYzKctE9K1OizCBRjAHJfXyoKAH0KdiPtgN20LUUh42MwODRDb3CAPh8d1J1NAzObRWC6F7vT5xNAQUZaD7GTyeADcALYd1S9UaonU01mcGiACskJBjqcILd-Gx-AJwNB4AAZHSxGRwZpQYGKURgNx0oZaXQABWxKlGWFkWnMujQghmACMAGpgNBCAAqHIw2E0aAwbCAA)
your description:\`请输入阶段${index + 1}阶段名称\` 模板字符串想匹配${index + 1}
执行  $('\`请输入阶段${index + 1}阶段名称\`').find('\\${$_$1}') 匹配不到，报 错误：Error: parse error!Missing semicolon. (1:23)

<img width="603" alt="image" src="https://user-images.githubusercontent.com/6399825/159454052-e249be06-9a04-4ef9-98d0-5b06a6d5d878.png">
<img width="490" alt="image" src="https://user-images.githubusercontent.com/6399825/159454088-3c342b54-562a-4257-af13-51df5f581c8a.png">

**Comment by shuerguo999** [comment]
模板字符串可以这样匹配⬇️
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIAGh36MGT4wU0VA2NMFbrAEmEnQA8ACAanoEYBfcwWBVAHzxxABoQAdyQAnANbJ0WEADMYEAMZwwSCPTiiAhhADOssQFsAFLLAAbNAEkIB-vS1Qw9pFBVrdASnrAAOuvpFDzh6CnoAXgcnADoAcyR4oPR-ekDg+l0kGFFFNAj6M0sbA2jM7NyU+gB6KvpRNDhs9QBPLNENbT0DUUM0FDT0egALNHrKoL0Q+t0YcxDIgG0AXUqKYzKctE9K1OizCBRjBYByHAoAfQoWKguKACY2W4BmHGOl7YDdtC1FIeNjMBwNCGbzhAB8Ph2qTqaBmc2isF0fzWgOB0UMWjgvwWdyWCwADEtohBUFs4mgIKNMWhjJ4PtD6Gx6TDGqJ1NNZnBogArJCQYzHXz+Y4fNj+ATgaDwAAyOliMjgzSgsMUojAbglQy0ugACvU4CpRlhZFpzLo0IIZgAjABqYDQQgAKkqMNhNGgMGwgA

**Comment by yaruiyang** [comment]
多谢，很棒
