### ISSUE TITLE
replace 方法无法转换函数入参存在默认值的情况

### ISSUE THREAD

**Issue by carl-jin** [thx/gogocode#143]
- version:
GoGoCode1.0.51
- playground demo:
[playground 例子](https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcI0A8pIBOcABAMZIQDOpAZkkiQLwkAUARgIaECMzJPADQkuhAEz8xASmYA+Edz4BqBeJCCQAdyIBrZOiwhaMCGThhKJOIU7V6hALataYADZoAkhHrDOUMMJIUOaUVDLAADoQJOShpAAk-H5gAHQA5kgZFOhRMRTUpFRIMIRkaPwu7l70KUUlZbkkAPRNJIRocCXRAJ7FhFY2dkQOaCix6CQAFmjtje2dhNHxrHWlaFIp7VCunGWsjQAG+TQk8QD68XwsrPG3MkzyESDn8WJPJAeCh8amIUsXPBudxIwDaHS6pwuEgAvgcohtCAw4KwNmk0BAZpw4GgUVFoVF1OBoPAADK2NKGODdKBoKhkQhgYKEyacKgABXm5hmWGsMDQGioMHYADUwGhNAAVakYbDWNAYaFAA)
- your description:

我希望将下面的这个代码

```ts
export const foo = (bar1 = 1, bar2 = 2) => bar1 + bar2
```

转换为

```ts
export function foo(bar1 = 1, bar2 = 2) { return bar1 + bar2 }
```

使用的 `replace` 语法为

```ts
$(source).replace(
  `const $_$1 = ($$$) => "$_$2" `,
  `function $_$1($$$) { return $_$2 }`
)
```

但是未能按预期执行，报错了，请看 [playground 例子](https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcI0A8pIBOcABAMZIQDOpAZkkiQLwkAUARgIaECMzJPADQkuhAEz8xASmYA+Edz4BqBeJCCQAdyIBrZOiwhaMCGThhKJOIU7V6hALataYADZoAkhHrDOUMMJIUOaUVDLAADoQJOShpAAk-H5gAHQA5kgZFOhRMRTUpFRIMIRkaPwu7l70KUUlZbkkAPRNJIRocCXRAJ7FhFY2dkQOaCix6CQAFmjtje2dhNHxrHWlaFIp7VCunGWsjQAG+TQk8QD68XwsrPG3MkzyESDn8WJPJAeCh8amIUsXPBudxIwDaHS6pwuEgAvgcohtCAw4KwNmk0BAZpw4GgUVFoVF1OBoPAADK2NKGODdKBoKhkQhgYKEyacKgABXm5hmWGsMDQGioMHYADUwGhNAAVakYbDWNAYaFAA)

看报错信息, 好像是将两个入参中间的 `,` 给删除了（或者替换为 `\n` 了？）。导致语法解析错误。
```text
/**
Something goes wrong...
Error: replace failed: function foo(bar1 = 1
bar2 = 2) { return bar1 + bar2 } cannot be parsed!
**/
```

要解决的话只能这样写

```ts
$(source)
  .find(`export const $_$1 = ($$$) => "$_$2"`)
  .each((item) => {
    let args = item.match["$$$$"];
    //  我们将 ast 中读取到的 入参 合并成字符串
    let argsStr = args.map((arg) => $(arg).generate()).join(",");
    let fnName = item.match[1][0].value;
    let fnContent = item.match[2][0].value;

    item.replaceBy(
      $(`export function ${fnName}(${argsStr}) {
      return ${fnContent}
    }`)
    );
  });
```

但是还是没有 replace 简洁

**Comment by shuerguo999** [comment]
gogocode@1.0.52 解决了
