### ISSUE TITLE
我开发webpack本地loader--一个去除console.log作用，引入使用后--报错如下

### ISSUE THREAD

**Issue by tangguolong** [thx/gogocode#144]
```js内容
const $= require('gogocode')
module.exports= function(source){
    return $(source).replace('console.log($_$)','').generate()
}
```
`
webpack下的模块配置，函数已经有走进去了
       {
          test:/\.(js)$/,
          include:paths.appSrc,
          loader:require.resolve(('../src/clearLog'))
        }
`

报错如下
Module not found: Error: Can't resolve './iterator.js' in 'C:\Users\Administrator\Desktop\桌面\currentPro\react-demp\react-demp\my-project\node_modules\gogocode\umd'

**Comment by bigfengyu** [comment]
在 node 端应该不会引用到浏览器端的 umd 文件呀，不知道是怎么配置的？

**Comment by tangguolong** [comment]
我关了吧，vue里面写没问题，因为可以在vue.jsconfig.js引入loader。
但在react里面，npm run eject被webpack配置弹出后，然后写一个loader或者插件，再到webpack里面使用，都会报错（直接用官方的webpack插件写法引入，也是报错-- failed! invalid input! accept code / ast node / nodePath）--有可能只能支持线上webpack插件
