### ISSUE TITLE
转换后的vue3代码vue2的风格

### ISSUE THREAD

**Issue by Butcher-hub** [thx/gogocode#147]
虽然转换后的代码可以在vue3项目中跑起来，但事实上这并不是vue3的编码风格，并且在文档中也没有看到相应的配置可以实现，例如非常好用的组合式API，setup语法糖。

目前手工编写的vue3风格应该都使用的组合式api了，若转换的vue2代码依然是vue2的风格，会影响整体代码的质量，造成风格不统一，而这依然需要手工修改。

还有就是vue3兼容vue2仅仅是为了过渡，相信在将来vue3将使用全新的代码风格，而那时将不在兼容vue2。

最后，支持阿里妈妈！

**Comment by bigfengyu** [comment]
基于配置的代码仍然是 Vue3 推荐的形式，我们的目标是最小化地修改 breaking change，让项目先升级到 Vue3，之后的新代码就可以自由使用新特性了。
