### ISSUE TITLE
Bug Report From Playground: Error: parse error!Missing initializer in const declaration. 

### ISSUE THREAD

**Issue by taomas** [thx/gogocode#149]
version 1.0.53解析异常

- version: 1.0.53
- playground demo: [link](https://play.gogocode.io/?v=1.0.53#code/N4IglgdgDgrgLgYQPYBMCmIBc4C2UkBOcABMMQIIBmlYAHsQIYDOxA+lTfQL7GUFI5iAcgB0IgPSs0THOIbU6QgNwAdCGrS18RYgGMkEJiQ51iAXjYnaq9RE3aS6SgxgAbEsDXEKC2gBo1LhsQPxAAd0IAa2R0LBBKGAhdODADYjgCBkNKQhwAChpXNABJCBy-RigwCqQoFIMmAEpSLz0GkgASc0qwEQBzJAH9dFb9QxImJBgCXTRuwpKypBFJ6dnW8XFiAjQ4aYhiAE8pgnTM7Ny0FDb0YgALNB3Wnb2CA4681Zm0RpEaCBQeSE9kIJDGRmIHVYHSEvz6aDsmTgaDyjUCahC4Gg8AAMlk+nE4IcoNJdAQwHVMXdmAAFF4pR5YDIwNChJgwABGADUwGgwgAVYkYbAZNAYLhAA)
- detail desc: 异常提示 `Error: parse error!Missing initializer in const declaration. `

version 1.0.45则解析正常
- version: 1.0.45
- playground demo: [link](https://play.gogocode.io/?v=1.0.45#code/N4IglgdgDgrgLgYQPYBMCmIBc4C2UkBOcABMMQIIBmlYAHsQIYDOxA+lTfQL7GUFI5iAcgB0IgPSs0THOIbU6QgNwAdCGrS18RYgGMkEJiQ51iAXjYnaq9RE3aS6SgxgAbEsDXEKC2gBo1LhsQPxAAd0IAa2R0LBBKGAhdODADYjgCBkNKQhwAChpXNABJCBy-RigwCqQoFIMmAEpSLz0GkgASc0qwEQBzJAH9dFb9QxImJBgCXTRuwpKypBFJ6dnW8XFiAjQ4aYhiAE8pgnTM7Ny0FDb0YgALNB3Wnb2CA4681Zm0RpEaCBQeSE9kIJDGRmIHVYHSEvz6aDsmTgaDyjUCahC4Gg8AAMlk+nE4IcoNJdAQwHVMXdmAAFF4pR5YDIwNChJgwABGADUwGgwgAVYkYbAZNAYLhAA)
- detail desc: 解析结果正常

请问这次版本升级后是一次破坏性改动吗，为什么会影响到老版本的代码解析逻辑。

**Comment by shuerguo999** [comment]
应该是底层依赖的解析器babel-parser升级了，规范写法应该是export const $_$1 = $_$2
