### ISSUE TITLE
希望增加一个find后的获取节点数量的api

### ISSUE THREAD

**Issue by ihupoo** [thx/gogocode#15]
我目前是 通过try catch `find`后返回的`ast`内的match 来判断是否有匹配到，如果匹配到，则通过循环判断匹配到几个 ，可否增加个 类似于 `getLength` 的api 获取匹配到几个？

**Comment by shuerguo999** [comment]
收到，已支持
gogocode@0.2.9
用法：
```javascript
$(code).find(`$_$`).length
```
