### ISSUE TITLE
Bug Report From Playground: 无法在注释节点前后插入新的节点

### ISSUE THREAD

**Issue by qqqiangqiang** [thx/gogocode#151]
- version: 1.0.53
- playground demo: [link](https://play.gogocode.io/?v=1.0.53#code/N4IglgdgDgrgLgYQPYBMCmIBcIDGSIDOcABAcQLzEDkAZnfVQNwA6EehJARhdQIb9NWrAPQAqUlF4AnKUgDuAWjzoAdLxQoAYmjQrOYFGVHDW7IsQi8Atmh7BWxYnitR8aCHAKZi9iI8eWNt5UKABeAI5UDsQAvqwxLGz4BEgANrqpSADmABRUAH6FRUVUAJSJIAA0IHJIUgDWyOhYIDQwbHBg+MRwUryENHVWOTRg6QCSEIOVxLxQYDNIUJ3JpT7RZiQAJDxzYCpZ2UjKaBvJJCkwUji2lKMTU0gql9enfsTCwsRSaHBXfgBPJBXHp9AZDNAoJyoWwACzQP2in2+v3+xC2OReN1KKh+UFSvBueU2sx4WwA+lsqDMqCTeDwAExlA7uBG8OBoHKlM4caHoACC5koGKxaG57xOgrgKlGEBQOQABmIJNJZIoTmoNNpdPpDMRjAqcWhCbCcjldU0xRQAHzrd6OZEWmF6NCDH55ABu0gs1luxCZ5WiDq+TtUvBoHKkeQAjAyAMwAFgArGVEv4PiGDJbcWh8YTOUrxARJDJ5EpneotDo9AYjMIFTTkcVm4VU0HiKHdF7UjAu7we7YANSUKifMfjqLvGLixw-P5SPySogsiBsjlc+KsKrgaDwAAy-SyLTgAKgaAIOCkYGW29hvAIAAU550EVher3qgQYJwAGpgNByAAKqeGDYL0OggDEQA)
- detail desc:
理论上通过识别 ``path.node.trailingComments`` 应该是可以实现这个能力的，不知道是我的用法不对，还是项目本身就不支持

**Comment by shuerguo999** [comment]
https://play.gogocode.io/?v=1.0.53#code/N4IglgdgDgrgLgYQPYBMCmIBcIDGSIDOcABAcQLzEDkAZnfVQNwA6EehJARhdQIb9NWrAPQAqUlF4AnKUgDuAWjzoAdLxQoAYmjQrOYFGVHDW7IsQi8Atmh7BWxYnitR8aCHAKZi9iI8eWNt5UKABeAI5UDsQAvqwxLGz4BEgANrqpSADmABRUAH6FRUVUAJSJIAA0IHJIUgDWyOhYIDQwbHBg+MRwUryENHVWOTRg6QCSEIOVxLxQYDNIUJ3JpT7RZiQAJDxzYCpZ2UjKaBvJJCkwUji2lKMTU0gql9enfsTCwsRSaHBXfgBPJBXHp9AZDNAoJyoWwACzQP2in2+v3+xC2OReN1KKh+UFSvBueU2sx4WwA+lsqDMqCTeDwAExlA7uBG8OBoHKlM4caHoACC5koGKxaG57xOgrgKlGEBQOQABmIJNJZIoTmoNNpdPpDMRjAqcWhCbCcjldU0xRQAHzrd6OC0wlSSH4eLl6NCDH55ABu0gs1luxCZ5WiDoMlud0nccHdvBoHKkeQAjAyAMwAFgArGVEv4Pl9Hao8QSiUrxAQXWqlE71FodHoDEZhAqacjih3CrmwwXiEXdH7UjAB7wh7YANSUKifGezqLvGLixw-P5SPySogsiBsjlc+KsKrgaDwAAy-SyLTgAKgaAIOCkYGWh9hvAIAAUV50EVhesPqgQYE4AA1MA0DkAAVa8MGwXodBAGIgA
