### ISSUE TITLE
转换后转义字符串中的空格丢失了

### ISSUE THREAD

**Issue by zhennann** [thx/gogocode#153]
- version: 1.0.53
- playground demo: https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIC2qYA2aAdGgB5RIBOcAzgAQC89AhlFEwHz3AA6E9egGMCLWgwBqaKrTBIB5OGggoGbKMRxo4LYgCE0LCHrFoe-QYLEBPCEPowoKFkoAUSKHDkRaASnMCloJgAGb07p7etMQAbtKy8kyMzACM-nyBQYIA9NnCVIZK9DoARkSYxWi0cAAqqEgWWYJC8tX0tACOBEz0AAaNTYIIAEoAogCCNaP0NeN6ADLTStV1KEjhA4PBKPSQcK4pafQAcgDyNScAqvPz9OOXNacA+gCSxyOjALKjxzUANJstkICi40ChxnBimAtNUWDgOGcLsdrrcACKjABi93mFwQl2GY1+TxqL2+AGVZp8AAoAzJbBxOUHgyFeGE6eEnc5XG70dFY664-GEmrE0mjCnjan0U7HeiXKmoybTPEEn4iknkyk0wGDdBEJQ7PYHI587EXADkAAZzbT6ZYwGBDRB9od-KaBfQrTadU0XEgcC8nS6TZizZ7rba7fR0LRgWBIokYiwqEIABbJ1wAJgArNm3aGPcibpG7VThqTxsMAJr0ADSoxrrkdvh9lhbdKCvQA3K2WAB3FhgFmpsDRIRwMiaVBoAjEDowaTWVydAi+Hsd+gAX0224gmxsdl2ECHES8rXSOtC4Q8Z58sXi3iSqQvG5yeRYKB2VCQRHoVDAADmqZ0K2LQ+JC35EMMgHAQwzAANqtoIwB-j+aDHHCaAVOaLDwKmyheEITI2qw47eNhwKFGg5pbiWgwoZB6GYdhuFwPhzpgERBokSwZHyNhIIoCRsYeExMIVJatFITwqFEBhWgsXhBGccRfykbe2F9v+SjCS0UBiVUElSa+lgMWh8lYZ6rHsYRqnqeRnp6to1FqSJ+kWbQRmbnRTRmXJzFWUpHFcWCPF8RAFEEPILntHpBmefQknedJfkGYpbHKSFQlqbxGmOTOzl6IQADWNHJSZyGyWlgUZcFdm5Q55rkJQNBFQQpXGXaqUWdhtDWNUaA4GFeXmoJumiR56U2Sp3GdYMAC665bP2g7DqOxDjpOJSGBAxCMcQH4oMMaHQUBcAmHAaauChfo4AgojiD1npwPUJGMadsFbmuOq7kEu77n1h7LPs6S-Vu-CNAUcAwFQAhSDI3jrpu64gH8IB9tQxXIOgWAgCEMB2LexRUEYtAhNQOCuCEYBEC8EDkzlUBgGpN5RC+zStJCAAkPRsGAxAAUggstOgjRgW0tBIDDQhmMw1O0-TSDEJL0toBDgTi5Csb-p4PRc8uUspmg7aCNr8ZwHtaBQKIMuuDhgP2I4zhuKz548FzTxc5uJH27YjuMi7CY+OkHte+aJv0Lk9AAco0igqwbQve0cD-hAAGQ9oMMCGbngC7HJNuO2u6o+A0DwPMRgAbjcDWPpOdwCX6a0FSUNeNIWApwuaMtPCyZoKc8CwA3mCd2gaO0DAJQSGAaB9jUtcYNgPdQH3ICbkAA
- your description: 转换之后代码中sql语句中的空格丢失了

**Comment by shuerguo999** [comment]
将在最新版本修复
