### ISSUE TITLE
文档内容描述有误

### ISSUE THREAD

**Issue by hjiog** [thx/gogocode#162]
![image](https://user-images.githubusercontent.com/42141272/172053359-ada70305-67ef-47fe-85a6-4b67a969ebc0.png)
使用`import $_$1 from '$_$2'`不能匹配形如 `import { useContext, rest } from '@as/mdw-hk';` 的代码，需要改成 `import {$_$1} from '$_$2'`

**Comment by shuerguo999** [comment]
playground链接中有给出各种情况的匹配结果，可以参考下，每种选择器匹配出的结果不同，文档会再更新下
