### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by flasco** [thx/gogocode#17]
- ~~`$ggcode(code).find("import $_$ from 'asd'") `不会返回 specifier 的 imported，默认使用 local 作为返回~~
    - watch [this comment](https://github.com/thx/gogocode/issues/17#issuecomment-829787492)
  - .attr() 的set/get 定义不支持返回节点数组(specifiers)，目前需要 ts-ignore

## 问题一
```
$ggcode(code).find(`import $_$ from 'components'`);
// 第二种写法 $ggcode(code).find(`import { $$$ } from 'components'`);
```

![image](https://user-images.githubusercontent.com/20221600/116552855-16234f00-a92c-11eb-84ba-4c9f28f7a0f3.png)
![image](https://user-images.githubusercontent.com/20221600/116553017-42d76680-a92c-11eb-99f9-c43ee8e8ac1f.png)

> specifier 是由 imported + local 组成，like this -> import { a as b } from 'c';

![image](https://user-images.githubusercontent.com/20221600/116553298-8e8a1000-a92c-11eb-8115-4627d412d3fe.png)

不知道是否是有意做了精简?

## 问题二，attr 的 ts 定义有问题，目前需要ignore

```ts
const item = root.find(`import { $$$ } from 'zent'`);

const curSpecifiers = item.attr('specifiers'); // 定义声明返回是个Node, 但实际上是 Node[], 所以还是要加 ts-ignore
// ... 几行逻辑

// 开始设置specifiers，这里originNodes作为Node[], 目前ts只接受Node / string, 所以这边写了 ts-ignore
item.attr('specifiers', originNodes);
```

（小声bb 文档有点简陋了     翻源码还比较好理解一点 /手动狗头）

**Comment by flasco** [comment]
```ts
    has(selector: Selector, options: FindOption): boolean;
    find(selector: Selector, options?: FindOption): GoGoAST;
```

has的options应该也是可选的才对

```ts
has(selector, options) {
  return !!this.find(selector, options)[0]
}
```

**Comment by flasco** [comment]
问题一这边调试了一下，发现是因为写法的问题，可以忽略。

原因记录
`import $_$ from 'xxx'` 在parse的时候会变成 `import g015613926536649103g from 'xxx'`;
这种情况在 astExplorer 中就是不会返回imported的，所以后续的 match 环节就会丢失 imported，可以通过写法来规避。

![image](https://user-images.githubusercontent.com/20221600/116646599-10208300-a9ab-11eb-96e7-20a2d5a2d871.png)

修完 type 之后就可以 close 了 XD

**Comment by shuerguo999** [comment]
非常感谢～我们稍后会merge pr
