### ISSUE TITLE
vue2使用vue-property-decorator后，无法做vue3的语法转换

### ISSUE THREAD

**Issue by lznbuild** [thx/gogocode#173]
如题，旧项目为了在vue2中使用typescript，使用vue-property-decorator 做了语法转换（见以下代码）， 发现使用gogocode不能做到vue3的语法转换，有计划支持一下这种情况吗

import { Component, Vue } from "vue-property-decorator";
@Component({
  components: {}
})
export default class App extends Vue {
  dialogVisible: boolean = false;
  storageVisible: boolean = false;

  created() {}
}

**Comment by shuerguo999** [comment]
使用 vue-property-decorator 的项目确实目前还没有好的升级方案
