### ISSUE TITLE
大佬们，想做一个精准匹配，应该怎么判断呀

### ISSUE THREAD

**Issue by 56496477** [thx/gogocode#175]
比如有个代码
const code = `
 intl.get('aaa');
 intl.get('bbb').d('bbb');
`;

代码转换：
$(code).replace('intl.get($_$)', 'intl.get(123)');
我只想匹配修改第一行代码 intl.get('aaa')， 不想匹配到第二个 应该怎么写

**Comment by shuerguo999** [comment]
可以(code).find(`intl.get()`).eq(0) 取到第一个之后 只操作第一个
