### ISSUE TITLE
$$$与$_$通配符有什么区别吗，replace替换时提示无法解析

### ISSUE THREAD

**Issue by Lnncoco** [thx/gogocode#179]
在使用`replace`做替换时，使用`$_$`会造成字符串重复导致错误，使用`$$$`则正常处理。
文档中没法发现对`$$$`的描述，能补充一下差异吗

 [复现例子](https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8c0C2UANgIb4B8AOhAAS04pgBuF+RZ+OA9E6zT3YlyaahAEBnAMYAnMFDhiwRJDLi1gtfBLgBGADRa0OgEy0AvrQBmMpAVpUQ2uAAVSUgNakA5mkcBuGho0AA8oVXV0K1IYYnVgGnoIUgI0TAcQABVjOEd9RNopO3CINAg4CXSEunojHQMC+mcTfJrzVvNAiB5pOQUKEH0QAHdVD2R0LBArGAgpODAkOjgZUggJK1UCAAorMGI0AEkITcNSKDBDJAVF9YBKDQKi9fUAEloAXlpzsAA6byQAKK6CeSx0tAkSBgMikaE+1n2RxOSF+kOhsNBLwhVikAEFwV9Xts0TC0IZNFBSDIJGgAPI3MFVWhkCDeGA+NK0ADkzBgaC5Fgsd0x4N68jg+PUXw2eJ0vz2EBQ2y5ODF-R6snFFC5wvENTVErlMjQwlh20a3OU4TUGlorwA+u9LDY7BlnG5PBzHFzWrVaAADK0RW0O15nFAoAByKThzts9kc7vcXl8jn9BV1BW43AhmoUkt+xtNaHNNWztS5QZtmletcFLoTThyHpTfhAPqzOfogZU1bttfDUZj9fjbubya9IHTZZzdy6BWNcGhdBlBd8pVW+G2uvMNEG4Gg8AAMmtvFNeRghgALUgSFyLhZoGRYaLEGlDCQwABGADUwGhhkyABPKAMGwIoiCpDBzCAA)

**Comment by shuerguo999** [comment]
https://gogocode.io/zh/docs/specification/basic#_-%E9%80%9A%E9%85%8D%E7%AC%A6
文档中有对$_$和$$$的区别描述，简单理解的话可以将$_$类比为正则表达式中的通配符`.` 将$$$类比为es6的扩展运算符`...`

**Comment by Lnncoco** [comment]
> https://gogocode.io/zh/docs/specification/basic#_-%E9%80%9A%E9%85%8D%E7%AC%A6 文档中有对$_和和$$的区别描述，简单理解的话可以将$_$类比为正则表达式中的通配符`.` 将$$$类比为es6的扩展运算符`...`

当我用 `ast.find('import {$_$} from "xx"')` 语句来匹配 `import { x } from "xx"` 语句，且只需要匹配这种导入语句时，$_$ 的结果是两个 x， 而不是实际的一个x，导致在`replace`时使用$_$就会报错了。对于import语句匹配出两个x，感觉有点奇怪，Object匹配出现这样比较直观能理解
