### ISSUE TITLE
如何查看变量的引用关系

### ISSUE THREAD

**Issue by zaiMoe** [thx/gogocode#196]
- version: 1.0.55
- playground demo:

是否有方式，像 babel 一样可以获取 `binding`， 判断是否有 `referenced` , 例如清除下面例子中没有使用的变量

https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBc4C2UkBOcABAIbEBmBSOxA5KXQDoRh6EkBGANMcJwEZunAEwBfStVp1OzVuyLEAxr2BKhy8ZJr0lclkqQQAzkgA2aAHRmkAcwAU6gJQBuFiwBupAsQgwcAsQAvPQAHuF0bhAUMBBKcGBGlBDE9k58LMRZykbGJH4BwcQCUdk5Jvn+IkUiUZnZhhW+-gDMRaQoKPYtvAAsru4p2QRocDAEKQW1g2UxcQlJHSippKu8nBvpwPVlWSNjE2SrxADUxBucpdliLDcQLBQQaSDcIADuhADWyOhYIHPxRIpOAEUgmCiEHD2ChgCwASWiSF4pCgYF4SCgCxMWx25TyxAAJO1UZZbHYkIZ0LjGvjTOMlGgijD4YjLHSCAzqbkSABBADKABUigT7OyGQMhlkAPRS4j7cYpACeSHGxBBYOMEIIODQy0pjIAFmgRjNsqa9qMFcR+QLSWgIMbSHA0Gl6mIXuBoPAADJg2x-OCKqBoYxKAhgTEeg2kYwABX2CWNWBBMDQr2MME4ADUwGg3gKgxhsCC0BgxEA

- your description:

**Comment by zhangdaren** [comment]
至少到现在，gogocode弄不了这活。scope作用域几乎不可用。
