### ISSUE TITLE
Bug Report From Playground: Your Problem

### ISSUE THREAD

**Issue by pyt111** [thx/gogocode#199]
- version: 1.0.55
- playground demo: [link](https://play.gogocode.io/?v=1.0.55#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8c0C2UANgIb4B8AOhAAS04pgButAxmQM6cC8A5ACNiSVH2p16DAIQBaGQyatmMsADMeVEBFRoAdATRxSBHcQCSKWlJ49aARk3suvTUJEoZbJBFVgA5jIEpJBGkJrikpI4aMQyAvBw3rRwAJ5QaBogUABOYEHZKY4AAhxgbADWmWwwnIkEYABeaOGA0kaAFUqAsomAdv44APQxcQneEVG9ihS0ciP0jCxOpNyZqsIA7jKcngAWpNlw4TSRkTgAYqsI27u02WjqfMtIK2wXcHy0ymqZUlIo5KS6EMZmiBaEVrtcIOhsvwwWgIWhsnxetNDtFYpwYmg2HBaLUUsQMpoVmAUHBNphaABmAAMVKgAA8ANyOd7qTRfH5Gf6Axy+Yj4bKkIRoJxoHaC-FvQKmTLo-FYgAq4qBtBIpDYaE2SGIkMygHfowCQCYBLo0AgZGAHBNAES+gBC3QAWEfsJIcogMkFA4GAkspVEgoZowPgCLRILQOX9tOgADJgWqOTDlNApTK+wi6YnR5ikYgwAngP3JlDR11wfGZACyAFF5QBBAAiFcrAH0AMqV+UAVQbtAA-LQAAYAEmAiYIuhQAgAcoCAL66fuD-SGUjBhAQccGCfd2jkvsDnMjldoKcznMGIzBvdr6NkAQxEvl6u1iuN5ttzs9w9J3eT6fbpPHhe-Jdnuum5vkOH6rl+s6-qek7duEfROi6boQMiRz9GiGJYsifTjAcUSyPIOAAELCKgyA+P4Vw3JkbioF45F+NGwb8HRvh+FWYDpkgfivEUNEoGRrEIOmxACGqlSCCR-HeIJwmiRUYh9MR7gCf4ExTLh2EsOIfR+qqlA0DQOCcGwuQuuIeRQF62KnA85w7NiqjZEg-p8EUvTMGAaArJwvReEQ3iwnAPkAAqkBAMR2bsvRQGFMR8DQFlWbQfiGFWKQAvUbDBUgtRIbQjnObQrnuZ53m+c5lnhRAQW9KF4XEJFcC9ClcBpRlZTZZwvpIfFEC9L0Ab+ZcSmkdJFEFS5ui9CNUn0bozCZr1iWXMAtBBFAADihj8pwtATvlTkuQtaB0r1J2WZc6CqKQMB8rQwC4RlaDkhJ7h8AANLhfmVYFnDkg99q0DZKyNbh9D9bQM0qQxEgTp9EjBrQAAUACU91g5RcAwNkdAAw6wb-XDGP0Cx-jsZxfj-cTkgeV1QrktdxDovDDr0AT90TtTROA-QobPRzLOHLKmJwIq9NFb1kSc7DgvffAaAoFTgO6Cr61bXAO1IwA2nwZaVjW9ZNrWbZ8AAuijuHc-QKzkE8SuRMLCpKsjabEGjeOHHRtQijsFbEMQABKCu0LYqMhxMHsOl72LVNk4Ktb8IfJJskbTtcqicLo9yPM8L6kqnvbp5n2dPPZuix-HVaJ+SEC3cQ1P0GoyMV4FVdGO7DeSC31VtyGOgRrUWdeqWaqbEjfPh+jPOs9HtAQFWhW2CgSDVAY1W6AAjpmBQNhhiTZEj3YAMR83W-Z87ma4W9PDpN+PC8EB3N+s3fF+1OQNQhzY9hP6zf9zw-XQuJ8S6DkuUPwTkYAQmQMIbISc+BHzQAIVQAAWVQABWSW-8pa0BiOiKe2CHTz2ckA1IICwEQKQFAqSsD4FH1UAAdlQaoVQWDCF7U7lLThe1r5-2lg6fhhw76u1-jPbw3s+YPyTsvVegVN7bxSLvOU+9D4nx0GfYArsr6d1fjoB+oi-6zz5mYHwSAk750zsGf4-dIxwCzpAFASM2CTzYLmL+tgRHcNntnKRS8V4wDXnYre8JFF7y9EjPgWdVjrC2PZPgvD-6z2Mk5f2AAJNA-hNjYlsD4khyStTEHSZkvYz8SbiOxPk-2AB1YkpIk65KHJU4gNSSSbC8eU2gSAWHojgEUvwWT6mrEAV0jOhg+lZPaRAb2IyektLqTkoZJCZmGDmW00p7AOnLNFs6JOkilndMMPKZ0kzpkHLgGGG42S556P2aM85lyTkVJMgUi5qgrkNKAc8-2rySnYKSV84gRyoCDIeIAppQLuH4mxHSd6tBCjrLvk01ZtAJhbNWQY-+d8tk-JRZ0s5yKAA+BLkZotqZsXF2LLm0AAGTUrxXc5F8hKVvIYLYAATDSFGGLsF0iTkjZl2IADUtA2UcsmPS2ZZKEnYP2ng4UkdCG8tsFSbh9BBF8NwUzeVqraBKtoCq9Z6qX6qGRk08Z2JUVnPNdy41JKzlAopVajJ-TsRErtXc81jq7kOtpRKsZzqBlMvtTsnAth0FUi5QQ9hcK+VbIdcKpGibjGmNoG64AE4UblxTtqcEqbiVa3NrofEEA-B1OFRSNGAAqEVdhxVbOtTq2VWqo3sJSEnA17CjUCM1fghVf823Ku4V2w4HzwVICRry6wHikDEn1S+Xl5Imk-NhW2qdbwZ2WCpC+Nti6AVAuvl4-Evt-ZB0cdK1mENAAbWYAOrlAAXCYAMCVABFfoAJyDuF7MaWQvQFDIHQK1F6OhGCRwjjYYcYdTbe2d28Ys-0fjZHr2CTvMJB9InZxiaXXY8TO6jr3eOqksKI2QaPdkP2gcFaoy5hjQRVs1pUOqsHMOANLaC2PJqFAf0W20AhnYXQtBAC4SoAac1ABoyhjBY6VnGQF9MjPmNqLHWPQLsnQ1NZ6rSerCvmA84CwuIJANAGm9pJ1IDbSTsmWq93HjoXMamLOpHSOe+gsnEa2BU4CKz4ZbFaZ03p4dUKgyJ1sAW6md8HO-CLZ52xRbYSls2BQCNHHIid0c8nVOLVOqum8OZ9AlnkjZEzHZyQENEsmcMKlpCSNiSwrgDltAeXwYDS9lqPQwg-ARO0+FDTH11PudoK13T7niR5YnHKvtkgrGde9rYMbdj1plb9JPYbkRZxPDADm2ESdFvZpQOCfQpAoBI3KHNnV5RdApxQOgOgOT0zokO7mPVfBT6vGFUdlM6z6DXCxjjWg5Qh2Zs4FZRNpBYUCDRjwCOOq75-BO2dm1f83vYzoA4F7+m5Vxf-rDj7MgEedu+4LP+s5iS3fu7QYVeOUA45fjmRIwLbCaGpPSTQZPb45nxCy6nIAKThrpyABnQicx6rsNzhbOYB36u4Wjugg5O4ZoSyFnren-Om07hR6esnwSQiRsGPL1NKNk64zxwAAHKAHYLQAs4mAAbTQAeRqAHnEwADqaADtjATwnAaiYgM4mEcI4FlZQDJlOmdHai2drYPgIGylTOxM5gwrneu1A8212x+nbCGeCNiIrCcjAe9hXwIwQoPo-2psFowScw9oAjxp6PkfsTecML5-P8vAsmqRnnv4svwvFqizF6HtBpfV6S5nFLOU0sQAy3ocr2XcudwK357vuhe+5XS8Pyro-n4Q3qyAprLWwu1A6zYqP3X1+af61zIbne+5ufG9ck-U2dszcIAdhFOYlsrfOwGO-G2tvTf2yDlHDojuQ9WxdrV138d4FCdHtcwdUxdPtvsgE-skYAdaAgcb92FwdjtiQodP9WZwDMdCFwNtVEdXtDA4dJhMCZVsduEScCd1EHsn8kxytSCKcdlWdac6R6daCkxmcrkacOcmCucWChw+cBdJBZxhcO1Ud8CPsJdn4pdn4rEm9T8Atn4lco4OlCtvcp9is+9Sth9GZ0Q8sVdYQ1cNdtcMYIY2UeNAB24MADXlQAIKDABOh0ABiVW3ETTgMTZKVKRONPZINIIvbrUgFIeEL3VOa4HpcjaeWeYMIOXaePIzJPFQ3sLJOAXbPgFqOsYSZIgEYgFIJoeJXQSyWoJGVaPwGAYkckYfKCX4eUTw8kGzLwlWItHw+EF8VaMgXwuBfaQmPaCrKrdPKJB4NDZ4TDaeMItASxGXHTPlQY4YzkHrPNWgAtTNabZxD-PIrDQ6ckAAeQEAACsRZdBYwUhOAnEUYtYqRTZ+DEhyQ2AtZ1itisQdi4x9i2BDjjiFdp4M1M1rgUAYB1RE0cgvDwo6Q4BgdQdn4jEdAk4fj7EIQ9tJ4jsJp3E54To7FYTfUjtEg4S-i7FEgasAw69pNMYCCfjO5wCtYaifi1METniBFYVZjqZxjhwQsJ5Q5aTRtQS3VZjttdsFiJgljn4ij2Ap9CjSdO5SijA9xziuRw8hT5xFxlxAQxS2AZSJSeTOAAA1UqMUjyLyU4UgPwfgmotgfg+-TbWEckJxLNZbI0ugVkwtN-Sebk7BXko7Aomg9ZYU0gUUz7cUovbhV0gCWUj0+Uvcfg+gGor7CQrlLmcMkIjpJ6NbPMaecAwvYvWxckJk+knQUvDTFM34cIukyY0Yo1ajWrSkHjQAQujAB070AFl5LoDGaffvZGYfSMION3G1HzRMs-MvDM2PfaWwBvamCGcswANidAByv0AGdFQAb58lMOkesIid8Y9B55iECxEQ9dUC9h1eYt9ETh5R4oSP95tJAjtDSttPRsgR4ngkYNjFz7S69XFYSbBbANjcx28HQ6Qs5Dok4ns4ysdEc75XFUS7zaAHz+s0DnzdA-yPTnsvyZUsTJCYdRC6AmCXi3iFZPi0BvjrgS94T-jAS0C74fiNMITHF38JgYS3z-z0TXzCpkTQKzEyKETqLI09y8D3s6A8LbFJce0cDsFwDWLB46I2ByBx4EToKuYqTzY+yBpABKJUAApXYc8c2w4cmwwAOw9AAs7SrOpkmwU3P3ZKvxgyBNx2f3NNzVsHW0MthG0qIuAo2WXMjGOAcSThkMRIcQnWhLcX-JfNhLdQ-LhJfMxO4W-xQN-ysBsocVFzgogLDKgN2H+0B2wsYuxORghwCogCfMkAwKHQ4ssqYoIIxyHUlyxPAPEIEUzV5H5CcUnmnIIp3OIoopg2-lcVnU8uorhPqs9zyxBPQE4GCiTlM3SmMA6nUPS0m1L04DmMv05Jwrr0bL0PqN9VNNnX-IauJVcUPLMt8EhIsq8oWtapStcXfixhnKINA0gxuyAIoKJz5IgpnjNIfyTmWpfzMptN3L8pOoD2APAs-JEOYvCr4XyrCrYAjMnOXOnK6tsAcu0vGr3JvNIqKjeqhucmOrAruzOuFV-KQEJL+oBvjLCrbMmxrh0E6s7NqHJGBuGo4UBkLM4wGhQR40ACY7QAZfMMZVd6j1dfh-DM5ex0T5QyhyhE1YrO5ZNC4bhi5Vh0NsRfUBai5uic4y4JM4AWb25MapYdcBpAAhG0ABI5K3QAEb9LRAA3PUADG0mswwEjUcDc5GbTWofnHfWoNlG1Wec2q5YklWe2y2mo+2tlCkw4cA+23Qd4lCtCjszCgEy8oROvHixyyE8alqtEui-rFK7i9CtiiQjKuK+OsvcubwfiuW9E4Sl40S89CmlqEjBys22xS2t222qc2PfzV20u2FGu62j2yIL28LX2r4pGMOskrC4OhbUOhOweNaxxSOmq6O-44e31VGkejEpABi0Kr6sO9i5HFOsKsO9O53AS7OyXESmYsS8msnQIyvBjXPFQ0bQEeBEDCm6oWoZyRoYUQ+5XFQ0mNiDiJrAvTuWmMAcWefL0qQ34f6WgGo2TCeMDQwwGPiaGISf2MBZueA4bCWoW0BSSR+n2oY1w1PHQh+saJ+imV+5+d+8WLQ7+v+dmdNBQkO6B9vWTWW+vFQ6TUhtVS2GgaWPoZJMAMyAyCAIyT9bwktfgYybgV4YyZ0BWcQBB9wKNTYANOAckOwGkAAUiZAkByO6m8HJGuDIFdGYDQAUbZkjFVBSAZnxEZFwmWBOhkCYGuCxCQnOK1ACQgG0f-r4k8EwcCGCGqlcY43wH+JkHTH8AgFUeKXsfoBilO0gACAECQA1mcmkdpCMcBmCaYBLRkFyBdXJA5XpHscESlt6Psg4xMbpGkcCc6U0eyGznJBukSEKaUf71UZiHIBYC0Yxl0AGF9xRyqasfyjADpAVkKde2KVSZiZ6eSGdGkYYTZXScowYYgCYd6GATQHEC5xABWC9HKGQHQCwBAFUCgUsaSEqzCk4GPIICRl5DQBMU9FhR2zAFhWdH7xGqjVnl7AMygDACny4hXkUwkCSSoWyHVHqWWxOdMSgOxnVFwghnAJSC+eyz2YOeDi8HkwkeuFwnAN7CRl+yBeq2QdVC+L4FnlICTl7DPmz2xY6VxfZSyJSnCgFHwGCOlgWcgFgHOTCj8HWeOgWe2E6re1dHhCwC-vehAE4BgAEFVK8nKPSHWe+h2AwAnCAA)
- detail desc:

**Comment by pyt111** [comment]
无法转换

**Comment by shuerguo999** [comment]
https://play.gogocode.io/?v=1.0.55#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8c0C2UANgIb4B8AOhAAS04pgButAxmQM6cC8A5ACNiSVH2p16DAIQBaGQyatmMsADMeVEBFRoAdATRxSBHcQCSKWlJ49aARk3suvTUJEoZbJBFVgA5jIEpJBGkJrikpI4aMQyAvBw3rRwAJ5QaBogUABOYEHZKY4AAhxgbADWmWwwnIkEYABeaOGA0kaAFUqAsomAdv44APQxcQneEVG9ihS0ciP0jCxOpNyZqsIA7jKcngAWpNlw4TSRkTgAYqsI27u02WjqfMtIK2wXcHy0ymqZUlIo5KS6EMZmiBaEVrtcIOhsvwwWgIWhsnxetNDtFYpwYmg2HBaLUUsQMpoVmAUHBNphaABmAAMVKgAA8ANyOd7qTRfH5Gf6Axy+Yj4bKkIRoJxoHaC-FvQKmTLo-FYgAq4qBtBIpDYaE2SGIkMygHfowCQCYBLo0AgZGAHBNAES+gBC3QAWEfsJIcogMkFA4GAkspVEgoZowPgCLRILQOX9tOgADJgWqOTDlNApTK+wi6YnR5ikYgwAngP3JlDR11wfGZACyAFF5QBBAAiFcrAH0AMqV+UAVQbtAA-LQAAYAEmAiYIuhQAgAcoCAL66fuD-SGUjBhAQccGCfd2jkvsDnMjldoKcznMGIzBvdr6NkAQxEvl6u1iuN5ttzs9w9J3eT6fbpPHhe-Jdnuum5vkOH6rl+s6-qek7duEfROi6boQMiRz9GiGJYsifTjAcUSyPIOAAELCKgyA+P4Vw3JkbioF45F+NGwb8HRvh+FWYDpkgfivEUNEoGRrEIOmxACGqlSCCR-HeIJwmiRUYh9MR7gCf4ExTLh2EsOIfR+qqlA0DQOCcGwuQuuIeRQF62KnA85w7NiqjZEg-p8EUvTMGAaArJwvReEQ3iwnAPkAAqkBAMR2bsvRQGFMR8DQFlWbQfiGFWKQAvUbDBUgtRIbQjnObQrnuZ53m+c5lnhRAQW9KF4XEJFcC9ClcBpRlZTZZwvpIfFEC9L0Ab+ZcSmkdJFEFS5ui9CNUn0bozCZr1iWXMAtBBFAADihj8pwtATvlTkuQtaB0r1J2WZc6CqKQMB8rQwC4RlaDkhJ7h8AANLhfmVYFnDkg99q0DZKyNbh9D9bQM0qQxEgTp9EjBrQAAUACU91g5RcAwNkdAAw6wb-XDGP0Cx-jsZxfj-cTkgeV1QrktdxDovDDr0AT90TtTROA-QobPRzLOHLKmJwIq9NFb1kSc7DgvffAaAoFTgO6Cr61bXAO1IwA2nwZaVjW9ZNrWbZ8AAuijuHc-QKzkE8SuRMLCpKsjabEGjeOHHRtQijsFbEMQABKCu0LYqMhxMHsOl72LVNk4Ktb8IfJJskbTtcqicLo9yPM8L6kqnvbp5n2dPPZuix-HVaJ+SEC3cQ1P0GoyMV4FVdGO7DeSC31VtyGOgRrUWdeqWaqbEjfPh+jPOs9HtAQFWhW2CgSDVAY1W6AAjpmBQNhhiTZEj3YAMR83W-Z87ma4W9PDpN+PC8EB3N+s3fF+1OQNQhzY9hP6zf9zw-XQuJ8S6DkuUPwTkYAQmQMIbISc+BHzQAIVQAAWVQABWSW-8pa0BiOiKe2CHTz2ckA1IICwEQKQFAqSsD4FH1UAAdlQaoVQWDCF7U7lLThe1r5-2lg6fhhw76u1-jPbw3s+YPyTsvVegVN7bxSLvOU+9D4nx0GfYArsr6d1fjoB+oi-6zz5mYHwSAk750zsGf4-dIxwCzpAFASM2CTzYLmL+tgRHcNntnKRS8V4wDXnYre8JFF7y9EjPgWdVjrC2PZPgvD-6z2Mk5f2AAJNA-hNjYlsD4khyStTEHSZkvYz8SbiOxPk-2AB1YkpIk65KHJU4gNSSSbC8eU2gSAWHojgEUvwWT6mrEAV0jOhg+lZPaRAb2IyektLqTkoZJCZmGDmW00p7AOnLNFs6JOkilndMMPKZ0kzpkHLgGGG42S556P2aM85lyTkVJMgUi5qgrkNKAc8-2rySnYKSV84gRyoCDIeIAppQLuH4mxHSd6tBCjrLvk01ZtAJhbNWQY-+d8tk-JRZ0s5yKAA+BLkZotqZsXF2LLm0AAGTUrxXc5F8hKVvIYLYAATDSFGGLsF0iTkjZl2IADUtA2UcsmPS2ZZKEnYP2ng4UkdCG8tsFSbh9BBF8NwUzeVqraBKtoCq9Z6qX6qGRk08Z2JUVnPNdy41JKzlAopVajJ-TsRErtXc81jq7kOtpRKsZzqBlMvtTsnAth0FUi5QQ9hcK+VbIdcKpGibjGmNoG64AE4UblxTtqcEqbiVa3NrofEEA-B1OFRSNGAAqEVdhxVbOtTq2VWqo3sJSEnA17CjUCM1fghVf823Ku4V2w4HzwVICRry6wHikDEn1S+Xl5Imk-NhW2qdbwZ2WCpC+Nti6AVAuvl4-Evt-ZB0cdK1mENAAbWYAOrlAAXCYAMCVABFfoAJyDuF7MaWQvQFDIHQK1F6OhGCRwjjYYcYdTbe2d28Ys-0fjZHr2CTvMJB9InZxiaXXY8TO6jr3eOqksKI2QaPdkP2gcFaoy5hjQRVs1pUOqsHMOANLaC2PJqFAf0W20AhnYXQtBAC4SoAac1ABoyhjBY6VnGQF9MjPmNqLHWPQLsnQ1NZ6rSerCvmA84CwuIJANAGm9pJ1IDbSTsmWq93HjoXMamLOpHSOe+gsnEa2BU4CKz4ZbFaZ03po1EN6BQqDInWwBbqZ3wc78ItnnbFFthKWzYFAI0cciJ3RzydU4tU6q6bw5n0CWeSNkTMdnJAQ2SyZww6WkJI2JLCuAeW0AFfBgNL2Wo9DCD8BE7T4UNMfXU+52g7XdPueJAViccq+2SCsd172tgJt2PWhVv0k9RuRFnE8MAObYRJ2W9mlA4J9CkCgEjcoC2dXlF0CnFA6A6A5PTOiY7uY9V8FPq8YVJ2UzrPoNcLGONaDlCHZmzgVlE2kFhQINGPAI46rvn8M7F2bV-w+9jOgDg3v6blQl-+8OvsyCR5237gs-6zmJPdx7tBhUE5QHjl+OZEjAtsJoak9JNAU9vjmfELLacgApOGhnIAmdCJzHquwvOls5gHfq7hGO6CDk7hmpLYW+t6cC6bTuFHp6yfBJCJGwYCvU0oxTrjPHAAAcoAdgtACziYABtNAB5GoAecTAAOpoAO2MBPCcBqJiAziYRwjgRVlAMmU6Z0dqLZ2tg+AgbKVM7EzmDCuf67UDzHXbH6dsIZ4I2ISsJyMF72FfAjBCg+j-amoWjBJwj2gKPGnY-R+xN5gavnDD+cL4r4LJqkYF7+PLyLxaYtxdh7QWX9eUuZzSzlDLEAst6Eq7l-LncisBf77oQfuVMvj+q5P5+ENGsgJa21iLtQus2Jj717fmnBtcxG73vubnJvXIvzNvbc3CBHYRTmFba3LsBif1tnbs3Dtg7Rw6E70P1srstVbtCd4FidntcwdUJdvtfsgEAckYgdaAQcH92FIdTtiQYdf9WZoDsdCFwNtVkd3tDAEdJhcCZVcduEycid1Ens38kxKtKCqcdl2d6c6RGdGCkxWcrk6cuc2CecOChwBchdJBZxRcO10diCvspdn4Zdn4rE29L8gtn4Vco4Olitfc59Ssh9ytx9GZ0QCs1dYQNctddcMYIY2UeNAB24MADXlQAIKDABOh0ABiVe3ETTgMTZKVKRODPZINIEvXrUgFIeEH3VOa4HpcjaeWeYMIOXaRPIzFPDQ3sLJOAfbPgFqOsYSdIgEYgFIJoeJXQSyWoJGVaPwGAYkckcfKCX4eUXw8kGzPwlWItAI+EF8VaMgQIuBfaQmPaKrGrTPKJB4NDZ4TDaeKItASxOXHTPlUY8YzkPrPNWgAtTNWbZxH-IorDQ6ckAAeQEAACsRZdBYwUhOAnEUYtYqRTZhDEhyQ2AtZti9isQDi4xji2BTjzildp4M1M1rgUAYB1RE0cg-Dwo6Q4BQdwdn4jEdAk4AT7EIQDtJ4TsJp3E54To7FETfUTtEgkSgS7FEg6sAwm9pNMYSCATO5oCtYGiAS1MUT3iBFYVFjqZpjhwwsJ5Q5GTxtIS3VFjdt9sViJg1jn4yj2A59SjydO5KijA9xriuRI8xT5xFxlxAQpS2AFSZSBTOAAA1UqKUjyLyU4UgPwYQhotgYQ5-bbWEckJxLNVbM0ugTkwtL-Sefk7BQUk7Eohg9ZcU0gSU77aUkvbhT0gCRUn05UvcYQ+gBon7GQrlLmaMiIjpJ6DbPMaeaA4vUvWxckNk5knQcvDTDM34aIpk2YyYo1ajerSkHjQAQujAB070AFl5LoDGefYfZGcfSMIOD3G1PzVMq-CvHM+PfaWwFvamCGaswANidAByv0AGdFQAb58lMOk+sYiD849B5liUCxEw9dUi9h1eY99UTh5R44Sf9FtJATtTSdtPRsgR4ngkYdjVznSm9XFESbBbAdjcxu8HQ6Qs5Dok4Xskycdkc75XFMSnzaAXzBssD3zdAgKfTXs-yZU8TZC4dJC6A2CPiviFZfi0B-jrgy9kTgTQSsC74ASNMYTHFv8JgESvzgLsTPzCp0TIKzEqKUT6LI0jyiDPs6AiLbFpce0CDsFoDOLB46I2ByBx4UT4KuY6TzYhyBpABKJUAApXcc6cxw8chwwAOw9AAs7TrOpmmwU2v25LvxgzBPx3f2tNzVsE21MthH0rIvAo2XXMjGOAcSTgUNRIcQnXhLcWAo-MRLdR-KRI-NxO4X-wwMAKsAcocXFyQpgKjLgN2EB2B3wtYvxORihxCogDfMkBwKHR4tsrYpIKxyHWlzxOgOkIEUzV5H5CcUnnnJIoPPIpopg2-lcVnV8voqROau9wKwhPQE4GCiTlM3SmMA6m0My2m3L04CWNv15IIqb1bKMOaN9UtNnWApauJVcVPKst8FhJsr8pWs6oytcXfixgXLINA0gzuzAJoJJyFJgpnitJfyTnWo-ysodMPKCouqD3AOgt-IkPYuir4WKqirYBjNnPXPnL6tsBcv0umqPIfMoqKi+rhucnOqgoeyuuFUAqQFJKBpBuTKiq7Omxrh0F6t7NqHJHBvGo4UBlLM4wGhQR40ACY7QAZfMMZ1dmjNdfhgjM5exsT5QyhyhE1ErO5ZNC4bhi5Vh0NsRfURai5+ic4y4JM4AOb25capY9cBpAAhG0ABI5G3QAEb9LRAA3PUADG0hswwEjUcHc5GbTWoQXA-WoNlG1Wea2q5cklWZ222ho52tlGkw4aA523Qb4jCrCns3CkE28oRJvAS1y2E6ajqrEpiwbDK-i7CrimQnKpK5OivcubwYSpW7E8Sj4yS89GmlqEjFyq22xW2r2x2uc+PQLT2yu2FBu+2n2yIP2yLQOv4pGKOqkvC8OpbSOlOweLaxxWOhq+O4E8e31TGienEpAFiyKv6qO7i1HDOqKqO7O13ES-O6XCShYqS6minUI2vBjfPDQ8bQEeBEDGm6oWoZyRoYUU+1XDQ0mNiDiFrIvTuWmMAcWZfP0uQ34f6WgBo2TCeMDUwwGPiaGISf2MBZuZA0bGWsW0BSSV+gOsYzw9PAwl+saN+imT+5+b+8WPQ-+v+dmdNFQiO+B7vWTRW5vDQ6TShtVS2GgaWPoZJMAMyAyCAIyT9fwktfgYybgV4YyZ0BWcQFB9wKNTYANOAckOwGkAAUiZAkAKO6m8HJGuDIFdGYDQBUbZkjFVBSAZnxEZFwmWBOhkCYGuCxCQmuK1ACQgH0eAb4k8FwcCGCGqk8Y43wGBJkHTH8AgE0eKWcfoBinO0gACAECQA1mcnkdpDMcBnCaYBLRkFyBdXJA5XpGccETlsGPsg4wsbpHkdCc6V0eyGznJBukSFKbUeH00ZiHIBYD0Yxl0AGH9zRzqbsfyjADpAVlKfe2KUyYSYGeSGdHkYYTZWycoxYYgDYd6GATQHEB5xABWC9HKGQHQCwBAFUCgVsaSGqzCk4HPIICRl5DQBMU9FhT2zAFhWdGHwmqjVnl7AMygDADny4hXkUwkCSSoWyHVHqVWwudMTgOxnVC+g6QWCuV7CRn+zBb8NWhimyHRE2MQnESAbIBLRgH1P5j4GOleH2gQrsu9l0m0eFET2Hrcr4DwEID0iWZ0lpbJYoGGND29g4ZdAM0pdhOpfZbgAoHYZMk4b5eGNwghlJfID0GuFVD+OpcUHmEWE0FIHCF7DPk0mYGZcz1mHVZVd7DVeZYSQhl5fQelcwr4FnlICTh1dzzNchaTjZTyJSnCgFHwHCLLOgJSD+dyyOZOeDi8HkxkeuFwmgKhc0KdYlfCOlhWcgFgHOTCj8G2eOhWe2F6o+1dHhCwD-vehAE4BgAEE1K8mqPSG2e+h2AwAnCAA

有语法错误，有两处 let data声明之后 又const data了一次
