### ISSUE TITLE
这个工具支持分析vue single file component吗

### ISSUE THREAD

**Issue by JeterLin** [thx/gogocode#2]
因为现在项目有比较多的代码是以前的开发人员复制粘贴形成的，特别是vue template code，想请问下这个工具支持对template的分析替换么

**Comment by shuerguo999** [comment]
感谢关注，请问你们是只需转换vue中的js逻辑还是template和js都需要转换？
如果是仅转换js，可以将js部分逻辑提取出来再使用现有的gogocode功能；
如果需要同时对template进行处理，我们很快就可以支持针对vue template的相关操作。

**Comment by shuerguo999** [comment]
gogocode@0.2.5版本已经支持对sfc的解析
```javascrpit
// 处理script部分：
$(code, { parseOptions: { language: 'vue-script' } })
.find()
.replace()
......
.generate()

// 处理template部分：
$(code, { parseOptions: { language: 'vue-template' } })
.find()
.replace()
......
.generate()
```
