### ISSUE TITLE
升级后，npm run dev 和npm run build 报错找不到vue

### ISSUE THREAD

**Issue by shangyawei** [thx/gogocode#218]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/11856639/234199803-e5cf9b4e-c978-400a-9754-be8c53ac3ed6.png">

**Comment by zhengwei-D** [comment]
我也遇到了这个问题，请问您解决了吗？

**Comment by zzuWanghao** [comment]
请问如何解决呢？我也遇到了这个问题。
