### ISSUE TITLE
模版字符串如何用函数包裹?

### ISSUE THREAD

**Issue by mystylemylife** [thx/gogocode#243]
demo:
```
 const a=`${a}11${b}`
```

如何实现下面代码
```
const a=$fn(`${a}11${b}`)
```

**Comment by shuerguo999** [comment]
const res = $('const a=`${a}11${b}`')
    .find({ type: 'TemplateLiteral'})
    .each(item => {
        const matcher = item.generate()
        item.replaceBy(`$fn(${matcher})`)
    })
    .root()
    .generate()
