### ISSUE TITLE
升级vue是排查多个规则不生效问题

### ISSUE THREAD

**Issue by feiyang420** [thx/gogocode#244]
在升级vue3时需要排除几个规则，单独排除某一个规则时都是可以生效的，但是多个规则同时排除不生效
gogocode -s ./src -t gogocode-plugin-vue -o ./src-out -p exclude-rules = emitsOptions
gogocode -s ./src -t gogocode-plugin-vue -o ./src-out -p exclude-rules = eventsApi
以上两个命令单独排除emitsOtions或者eventsApi时均可以正常生效
gogocode -s ./src -t gogocode-plugin-vue -o ./src-out -p exclude-rules = emitsOptions,eventsApi
但是通过排除多个规则命令时无法正常生效

**Comment by 321638914** [comment]
试试用`#`来分割参数，cli的帮助信息里面写的：
https://github.com/thx/gogocode/blob/9e1915ed12ca3ba6803a25782a2db0fde46e2f8d/packages/gogocode-cli/index.js#L26
