### ISSUE TITLE
Immediately invoked function

### ISSUE THREAD

**Issue by tomsej** [thx/gogocode#25]
Hi, thank you for this awesome tool. Really love that and it helped me a lot. But I am struggling with one example -> immediately invoked functions. I have function like this:

```js
(function(param_1, param_2) {
    // Code that runs in your function
})({"config": {...}, "data": {..}}, {"actions": {...}, "misc": {...}})
```
I need to extract parameters of this function `{"config": {...}, "data": {..}}, {"actions": {...}, "misc": {...}}`, can you please help me how to achive that?

Thanks a lot!!!!

**Comment by shuerguo999** [comment]
Hey, @tomsej , thank you!!
You can look up this example: https://is.gd/RIJDYs

**Comment by tomsej** [comment]
Thanks a lot!!
