### ISSUE TITLE
antd 样式没生效

### ISSUE THREAD

**Issue by Go7hic** [thx/gogocode#26]
看测试用例里没有引入 css 文件
![image](https://user-images.githubusercontent.com/3821390/122917818-03a81d80-d391-11eb-9a1d-a16b5a2c5453.png)

然后我自己试了一下也没有生效，配置如下：
```js
const importPlugin = require('esbuild-dynamic-import-plugin')
const esbuild = require('esbuild')

esbuild.build({
  plugins: [
      importPlugin({
          options: [{
            libraryName: "antd",
            style: true,   // or 'css'
          }],
      })
  ]
})
```

**Comment by kooriko** [comment]
收到，我看下

**Comment by kooriko** [comment]
我们在版本 0.0.10 修复了这个 BUG
请先行使用 0.0.10 进行开发调试
![image](https://user-images.githubusercontent.com/28329518/123212657-aaa6c980-d4f7-11eb-8537-853f8baf50ec.png)
