### ISSUE TITLE
对html模板的注释，非人为操作，自动添加了多余空格

### ISSUE THREAD

**Issue by qq974837057** [thx/gogocode#28]
解析模板
`<!-- html模板的注释 -->` 
使用这段代码解析，什么都不做，注释被自动加了前后空格
`function transform(fileInfo, api, options) {
  const $ = api.gogocode
  const source = fileInfo.source
  // 在这里返回你生成的代码
  return $(source, { parseOptions: { language: 'html' } })
    .generate()
}
`
求教是使用方式有问题还是代码问题呢~

**Comment by shuerguo999** [comment]
感谢反馈，已解决，辛苦升级gogocode@1.0.4

**Comment by qq974837057** [comment]
> 感谢反馈，已解决，辛苦升级gogocode@1.0.4

尝试了一下，使用1.0.4 仍然存在这种情况，麻烦再验证下看看~

**Comment by shuerguo999** [comment]
> > 感谢反馈，已解决，辛苦升级gogocode@1.0.4
> 
> 尝试了一下，使用1.0.4 仍然存在这种情况，麻烦再验证下看看~

确认没有问题，麻烦确认一下node_modules版本号是不是大于等于1.0.4。可以打开这个链接看一下～如果仍然有问题，辛苦把样例代码贴在playground中反馈给我，感谢
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8BCAWgIAIBnc4ogPhABoQB3JAJwGtl0sQAzGCAYzhgkEYnGYBDCKW4sAtgApuYADZoAkhFm1iEqGB1IoQkaQCUxYAB1RxfqbjEAJMQC8u-QDoA5kl-30G2I7BzIkGGZ+NDdiZTVNWU9ScMi0IOIAegziQAp1QE34wBnEwBX4wD21QAN5QHxXQAQjQBC3QGO5QEAPdOY0OAjRJwVkiKidYGIoCWZSNAB5Y2FpTGIAcgALODkVGeIAXzMfNAg0STg0BTMbVZs6cGh4ABkpby4FpdO5iVIABRa4IR2scRg0ens5QYtUbwWBwL7MH6rIA

**Comment by qq974837057** [comment]
升级 gogocode-cli@0.2.16 正常了

**Comment by qq974837057** [comment]
升级 gogocode-cli@0.2.16 正常了，谢谢~
