### ISSUE TITLE
vue2.6 利用 gogocode 升级3.0后运行报错

### ISSUE THREAD

**Issue by XHHZYQ** [thx/gogocode#29]
1. Cannot read property 'Component' of undefined
2. window.$vueApp.use is not a function

**Comment by bigfengyu** [comment]
第一点麻烦把具体报错的代码片段截取出来，第二点需要您调整顺序，文档里有写哦

**Comment by XHHZYQ** [comment]
1. 第一点报错的代码片段，App.vue文件：

`    <router-view v-slot="{ Component }">
      <component :is="Component"></component>
    </router-view>`
2. 第二点报错的代码片段，main.js 文件

import * as Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'

window.$vueApp = Vue.createApp(App).mount('#app')
console.log('window.$vueApp : ', window.$vueApp)
window.$vueApp.use(router)
window.$vueApp.use(store)
window.$vueApp.routerAppend = (path, pathToAppend) => {
  return path + (path.endsWith('/') ? '' : '/') + pathToAppend
}
第一次用公司项目转换后报错，改用cli 4.15.x搭建的vue2.6.11初始化的项目进行升级也报同样的错
抱歉！图片一直上传不了，将就着看吧

**Comment by kooriko** [comment]
请升级 gogocode-cli 0.2.8 即可！
