### ISSUE TITLE
vue-cli3.x的项目尝试了下转化失败

### ISSUE THREAD

**Issue by FoneQinrf** [thx/gogocode#30]
<img width="569" alt="WechatIMG51" src="https://user-images.githubusercontent.com/22515091/123403140-0d24c600-d5db-11eb-94d8-0a7854238fdf.png">

**Comment by bigfengyu** [comment]
当前对yarn支持可能有问题，建议先使用npm安装

**Comment by FoneQinrf** [comment]
<img width="565" alt="WechatIMG53" src="https://user-images.githubusercontent.com/22515091/123729996-638a5100-d8c8-11eb-9f24-09c4b636d7f0.png">
npm安装的

**Comment by FoneQinrf** [comment]
gogocode版本0.2.6

**Comment by FoneQinrf** [comment]
> 当前对yarn支持可能有问题，建议先使用npm安装

npm安装的
![Uploading WechatIMG53.png…]()

**Comment by FoneQinrf** [comment]
> 当前对yarn支持可能有问题，建议先使用npm安装

npm的方式
<img width="565" alt="WechatIMG53" src="https://user-images.githubusercontent.com/22515091/123731272-68500480-d8ca-11eb-8c73-1eab44141d39.png">

**Comment by wudi3** [comment]
缺少-t 参数，可以试下下面命令：
gogocode -s ./gcp-web-financial-operation -t gogocode-plugin-vue -o ./gcp-web-financial-operation-3
