### ISSUE TITLE
Async function return type wont get matched

### ISSUE THREAD

**Issue by loicnestler** [thx/gogocode#31]
Given the following input code:
```typescript
export default async (
    data: Request<{ msg: string }>
): Promise<string> => {
    console.log(`Received echo request: ${data}`)
    return data.msg
}
```

This code:
```typescript
 const match = ast.find(`export default async ($$$1): $$$2 => { $$$3 }`)
```
Wont match `$$$2` at all (only `$$$1` and `$$$3` are getting matched).

If I change `$$$2` to `$_$2`, then the match will be `Promise`, but without the generic.

Is there a workaround for that?

Thanks!

**Comment by shuerguo999** [comment]
Thanks a lot!!! gogocode@1.0.4 fixed it.
`const match = ast.find('export default async ($$$1): $_$2 => { $$$3 }')`
