### ISSUE TITLE
find(`class $_$ {}`).before(`@decorator()`) ，无法给class加装饰器方法

### ISSUE THREAD

**Issue by alonezjh** [thx/gogocode#32]
无法给class加装饰器方法

**Comment by kooriko** [comment]
@shuerguo999 来看下这个问题

**Comment by shuerguo999** [comment]
1.0.11支持啦
$(`class A {
    }`)
    .find(`class $_$ {}`)
    .before(`@decorator(a, b)
    @decorator11(a, b)
    `)
    .root()
    .generate()
