### ISSUE TITLE
对html中匹配的字符串不能直接替换

### ISSUE THREAD

**Issue by qq974837057** [thx/gogocode#39]
![image](https://user-images.githubusercontent.com/45394150/125055560-e8037d80-e0d9-11eb-9160-4ef6eaa959a7.png)
是我使用方式不对吗，求解答~

**Comment by shuerguo999** [comment]
已解决
![image](https://user-images.githubusercontent.com/8147254/125420732-ea729ae5-9351-440b-b9e7-7d6bf33d0f0b.png)
