### ISSUE TITLE
怎么循环遍历并修改其中的节点属性呢？

### ISSUE THREAD

**Issue by Chrisyjs** [thx/gogocode#4]
`
AST.find('const $_$1 = _import($_$2)').each(node => {
  const temp = node.match
  map.set(temp[1][0].value, temp[2][0].value)
})
AST.find('component: $_$').each(node => {
  const temp = node[0]['match'][0][0].value
  node[0]['match'][0][0].value = map.get(temp)
})

`

**Comment by shuerguo999** [comment]
第二段第三行代码改为：node[0]['match'][0][0].node.value =map.get(temp)就可以了。
原因是：match中的node和value，node是AST节点引用，可以被修改，而value是节点输出的字符串，修改不能生效

0.1.3版本支持更简单的方式：replace第二参可以是函数
AST.replace('component: $_$', (match) => {
 return `component: ${map.get([match[0][0].value])}`
})
感谢支持～
