### ISSUE TITLE
转换后会把js的分号全部去掉

### ISSUE THREAD

**Issue by kstd123** [thx/gogocode#41]
https://play.gogocode.io/
playground展示的也是会去掉分号，这个能配置么。

**Comment by shuerguo999** [comment]
如果是使用gogocodoe进行vue升级，需要升级最新的gogocode-cli，增加参数format就可以gogocode -s src -o src -t gogocode-plugin-vue -p format=false
如果是直接使用gogocode，generate()不传prettier就不会去掉分号，另外要注意replace第二参也需要加上分号
