### ISSUE TITLE
replace第二个参数可以支持函数么？

### ISSUE THREAD

**Issue by jiangtao** [thx/gogocode#42]

**Comment by jiangtao** [comment]
场景：
```Vue
<template>
 <div style="margin-top: 10px; color: red;"></div>
</template>
```

output

```Vue
<template>
 <div style={{ marginTop: '10px'; color: 'red'; }}></div>
</template>
```

**Comment by shuerguo999** [comment]
replace第二参支持function，可以参考这个例子：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8KwBuABAQLQC2qaANgLwA6IAhowHw4D0+BrIANCADuSAE4BrZOiwgAZjAgBjOGCQQicEUwgBnGaPIAKGWGpoAkhD18iTKGGtIoy1doCURYPTVEFLuEQASIlobOwA6AHMkKN90LyIfPyJtJBgRBTRgomNTCz0wlLSM+KIODiJACnVATfjAGcTAFfjAPbVAA3lAfFdABCNAELdAY7lAQA8SkTQ4NLUAg0L0tGtgIigmEW00AHknFR1MDyJqLQiYJgi0dYByAAs4cmpDgF8iS9cSsIGoLYyDAAMcAIB9AIBGEgoqHRGF8AgAmRiBAIBdgcEE-VivazkJhwBTHYKsDwlBK+HT+AgAWUBADUmNQYJkQsjUccANqggC6tIADAywgQyRSANzYogDIYiNTvOH-SjoIEgALAQkkzloS4QiBoQQAQTgGgYICVgilMvFpPJ8ohUOhnDhrxKt3uIiQSDgBju3kiaCVmjgaAdXgVEH44Gg8AAMttpKdzr7jkxtAAFfnKNAiLAaCkCXzkWYDRbwWBwRMiCmXIA
![image](https://user-images.githubusercontent.com/8147254/125601289-b78e0b1c-fdcd-46c9-a508-b42b8f0de923.png)
