### ISSUE TITLE
如何找到对象中属性a,根据规则替换属性b

### ISSUE THREAD

**Issue by daisybaicai** [thx/gogocode#52]
```js
const obj = {
    '学生': 'student',
    '教师': 'teacher',
    '厨师': 'cooker'
}

const descList1 = [{
    index: 1,
    name: 'name1',
    desc: '学生',
}, {
    index: 2,
    name: 'name2',
    desc: '教师'
}, {
    index: 3,
    name: 'name3',
    desc: '厨师'
}];
```

=>

```js
const descList1 = [{
    index: 1,
    name: 'student',
    desc: '学生',
}, {
    index: 2,
    name: 'teacher',
    desc: '教师'
}, {
    index: 3,
    name: 'cooker',
    desc: '厨师'
}];
```

**Comment by daisybaicai** [comment]
```js
const $ = require('gogocode');

const obj = {
  '学生': 'student',
  '教师': 'teacher',
  '厨师': 'cooker'
}

const res = $(`
const descList1 = [{
  index: 1,
  name: 'name1',
  desc: '学生',
}, {
  index: 2,
  name: 'name2',
  desc: '教师'
}, {
  index: 3,
  name: 'name3',
  desc: '厨师'
}];
  `)
  .find(`{ name: $_$1, desc: $_$2}`)
  .each(item => {
    // item.node			// 包含color属性的对象
    // item.match		// color的值

    const nameValue = item.match[1][0].value;
    const descValue = item.match[2][0].value;
    const ast = item.node;
    console.log('name', nameValue,'->',obj[descValue]);
   // TODO: 这块代码，显示错误拿不到attr属性
    ast.attr("name", obj[descValue])
  })
  .root()
  .generate()

console.log('res', res);
```

```
    ast.attr("name", obj[descValue])
        ^

TypeError: ast.attr is not a function
```

我想要直接修改这个ast的name属性，该怎么弄？

**Comment by eyis** [comment]
AST对象才有attr方法，例如demo里的item.attr('xxx')，它的node是没有attr的
另外这种对象操作直接用js操作更方便些

**Comment by shuerguo999** [comment]
1.item.node是没有attr方法的，item有attr方法
2.item.match[1][0]包含两个属性，value和node，value只读，node是具体的节点，可以进行修改，节点结构可以断点查看。因此操作item.match[1][0].node就ok了：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIDGSIDOcABOgTgDJhECMxAvMQNrAA6Exxk6AHpsTQA07ThACGAWzT8A5OKk0ZwjqTTlZgM21A+K5L2AX0HE2K7mj7EATMtGTpxObYu6VZHLMCapoAg9GfsPHOpuYAzNbE8nYOUkHOnK6ygBXK3voAugDcIIIgAO5IAE4A1sjoWCAAZjAQOHBg+MRwuWKEpXkSABSlYAA2aACSEM2GYlBghkhQ1fgEAJRGIsR4hCQAJAzEQ2AAdADmSDt46HMLRMQESDC5OGirHd19zRun55dzAPQvxIAU6oCb8YAziYAr8YA9tUABvJaQAIRoAQt0Ax3KAQA9DpMSEgAEYAK1W-ns2hksiIMHQEDgMXsXix9jgaDEOAAFmhcoSZIkSTI8Eh8jSfBA9HNcmg4OcOEtWo8LmgpnMNh0IChWgADYBhWz8JYAfSWQlU6mIyqWFj00tFKg25KprTAZIkDAAfLMVJw3lwzRsIKg0Kw4K7XXbAKDKgGoVPCdPKAPR1AOQG4MAn9qAQxi5rb3qa0BINhIxHAqe64Ha-XlwYAeBXYUfm8PlUgAamJOjAroxY-HE8nKUwaMkmAAGZIbABupfLqTzRxIrhLZYr9rjCaTVKYFkbLfbnbQ3Zt+cWa2OlYdTvQ884AQdNfHDebrfXaBng9WSORTH7s+Scz0+s4G1ySCQcFa9+I2zQEBpSbQb-07AZOA0DwBQjRbCUcAAJ5QGoOC5GA4xAZSYgEAACtycDVDSWD1OWmR4BIUBiNyADy8CwHAuG5OWehAA

**Comment by daisybaicai** [comment]
非常感谢！
