### ISSUE TITLE
涉及到作用域的替换应该怎么弄？

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#53]
如下代码：
```
var n = {};
n.n = square(10);

function ajax(){
    console.log(n)
    $.ajax({
        url:"",
        success:function(n){
            console.log(n)
        }
    })
}

function square(n) {
    return n * n;
}
```
如果我想把上面的代码转换为：
```
var number = {};
number.n = square(10);

function ajax(){
    console.log(number)
    $.ajax({
        url:"",
        success:function(n){
            console.log(n)
        }
    })
}

function square(n) {
    return n * n;
}
```
应该怎么实现呢？

前提：n所在的函数名不固定，位置也不固定。

**Comment by shuerguo999** [comment]
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIBuBDAJwAIIiBeI4AXwG4AdCCAOlIoGcBHGQtACgEYADAEp6EBgDMYEAMZwwSUngBWeAB69hwBkV1EZitkgA2aJsaQBzXhGE69AEiYr1vbaT2eYBY5joh-ABp7T102GBkZNDY2TClZeUUbLRDQzwMII1NzK2TUzypUqjsIQvEIeLkFUk5uAj5bSlT6uG9SUgAqEjEqEECQAHckAgBrZHQsEErE0jgCPEyJYYBbXgkwUwBJCqRAojwoMD2kKBm2YSaPDLY4IgdyfcOmSyskA3R7a9ujbyiH9a2OyYPwIUXsAHpwURABTqgE34wAziYAV+MAe2qAA3lAPiugAQjQAhboBjuUAgB72Uy3epsMS6UkPBy8EFRYRMdYQFC8ADkEBZJV0TDQeBkAAsbOQAHyXTxgCREGwAbUEAF0WKg0AAFPBwPnAgxQMwWJAjGBQVns+lgNgAcQsACM8MYiAAyW0kGXyiCKlVqlh4ZZoIgAQjIFBZUAIJzQBDgAE8OaLQsx6lBjLy0AAhcOstQcor2Yr2JjBpBwTQ5yxoCCh1V8TlEewtNpEUkMMp9cDQeAAGQWlkmEa1bBkBDApybfLwbCVLXkoawEmtbDQ-QMyygPAA8vBYHAsHMYGgqEA
