### ISSUE TITLE
在html/vue里面对dom节点使用empty函数不生效

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#55]
复现地址：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8A3MNAdwAIBjAGwEMBnGgXgB0QqAjM5gPkYhL5PyEinEsGAkAtmjpUA5mhIBfRQID0BYt179Bm0eKkz5SlTnVCt-ARuH7J0mnIXK1Nyzrd3Dj4y7NuefwseHhAAGhAiJAAnAGtkdCwQADMYCDI4MCReOGiqCBpkmIkACmSwCjQASQgisJIqKDB6pChM7JoASlEePjIOuBIAEhJ6BqaAOlkkaf70XvIBkhokGGiyBTHyypqiiZW1jYXVVRJACnVATfjAGcTAFfjAPbVAA3lAfFdABCNAELdAY7lAQA8FysHo6QLAE0UbDEoHdZoerABZ8KBUaI0NAAeTaWQKmB62is1AgshgTkxAHIABZwCQUIlhWFKanaRSdGkTcoQFAlIk4IYAfSGcDk5GodCYLHYXDM3N5ck4RMZ2JIEzQVDIJLKaQy6JIJTAcDQEm6MLlfDwCJIwNB2t1CokbQAniVZVY+h0kJUJhQZuzgVTTdIHfwGUzokgkHB7Uz5BA0HkdWGIEC0HA1rxgTxFKEIpBYHAADL5WRJMkU8IgEm0AAKALgmSjWGSVAoSIi-WtCJR8CzWFyMDQiiAA

Ast.js
修复参考代码：
    empty() {
        if (Array.isArray(this[0].nodePath.value)) {
            this[0].nodePath.value = [];
        } else if ( Array.isArray(this[0].nodePath.value.content.children)) {
           this[0].nodePath.value.content.children = []
        } else if (this.node.type == 'File') {
            this.attr('program.body', [])
        }
        return this
    }

**Comment by shuerguo999** [comment]
1.0.26版本已修复
