### ISSUE TITLE
append可以像数组的push(...array)函数一样，支持数组嘛

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#56]
地址：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8A3MNAdwAIBjAGwEMBnGgXgB0QqAjM5gPkYhL5PyEinEsGAkAtmjpUA5mhIBfRQID0BYt179Bm0eKkz5SlTnVCt-ARuH7J0mnIXK1Nyzrd3Dj4y7NuefwseHhAAGhAiJAAnAGtkdCwQADMYCDI4MCReOGiqCBpkmIkACmSwCjQASQgisJIqKDB6pChM7JoASlEePjIOuBIAEhJ6BqaAOlkkaf70XvIBkhokGGiyBTHyypqiiZW1jYXVVRJACnVATfjAGcTAFfjAPbVAA3lAfFdABCNAELdAY7lAQA8FysHo6QLAE0UbDEoHdZoerABZ8KBUaI0NAAeTaWQKmB62is1AgshgTkxAHIABZwCQUIlhWFKanaRSdGkTcoQFAlIk4IYAfSGcDk5GodCYLHYXDM3N5ck4RMZ2JIEzQVDIJLKaQy6JIJTAcDQEm6MLlfDwCJIwNB2t1CokbQAniVZVY+h0kJUJhQZuzgVTTdJZTSjSaKGAaIMxgBtf38DluACMQU0VMjfGjFgATPHhInDVHdMIAMwZ6V0x0kAC6kYtEgmjSgaFZJQmjaDIYd-AZTOiSCQcHtTPkEDQeR1vYgQLQcDWvGBPEUoQikFgcAAMvlZEkyRTwiASbQAAoAuCZQdYZJUChIiL9a0IlHwRdYXIwNCKIA

比如，push是可以支持数组的
var list = [1,2,3];
var newList = [666];  
newList.push(...list);
console.log(newList)

//输出： [666, 1, 2, 3]

**Comment by shuerguo999** [comment]
1.0.26版本已支持
```javascript
xx.append(`<view>1</view>
      <view>2</view>
      <view>3</view>`)
```
