### ISSUE TITLE
 .replace("!0", "true") 引起误杀

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#57]
复现地址：https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIBuBDAJwAIwBnAFQJjSIF4iBCABgG4AdCfYsgMTwBtSNegwCMLEABoQAdyQEA1snRYQAMxgQAxnDBIIROATwRSa+QFsAFGrD80ASQjnJRPFDCukUXftIBKImAOIiItPzgiABI6Nw8AOgBzJGTw9BCwiKJSJBgCLWEiW3snc3icvIKMgHpqokAKdUBN+MAZxMAV+MA9tUADeUB8V0AEI0AQt0BjuUBADwyCNDg8gyirCvy0fwz48ah+PAKrNhBmLdcto2otxYMiZaQkOCt-JLQINGM4NCuOAF8OKXBoeAAZE0TVOAATygaFIWgIYB8HwAFnhSAAFcZwXT3LAHNDScIWKCENAAeXgsDgaKoaBeQA

连同!1也转换了，，这种情况，只能使用{type:"UnaryExpression"} 这种匹配了。

**Comment by shuerguo999** [comment]
1.0.26版本已修复
