### ISSUE TITLE
find可以只找到子节点而不是所有深度节点么？

### ISSUE THREAD

**Issue by wztscau** [thx/gogocode#59]
`{aa: {aa: 1}, b: 2}` 可以只 find 到最外层的 aa 而不是内部的 aa 么？
那怎么判断我 find 到的 aa 是在第几层啊？

**Comment by zhangdaren** [comment]
如果第一层好办，直接$(code)就是第一层，$(code).attr(xxx)，这么用。 今天刚好碰到这个问题了。

**Comment by wztscau** [comment]
> 如果第一层好办，直接$(code)就是第一层，$(code).attr(xxx)，这么用。 今天刚好碰到这个问题了。

不是的，我指的第一层是基于对象的层级，而不是 ast 的层级。以上我的例子不能只 find 顶层而不是内层的 aa

**Comment by zhangdaren** [comment]
> > 如果第一层好办，直接$(code)就是第一层，$(code).attr(xxx)，这么用。 今天刚好碰到这个问题了。
> 
> 不是的，我指的第一层是基于对象的层级，而不是 ast 的层级。以上我的例子不能只 find 顶层而不是内层的 aa

find(`{$$$}`).each(function(item){ console.log(“这就是第一层：”, item.match["$$$$"])})

打印出来的，就是第一层。。

遍历一下就知道了有哪些元素了。

**Comment by shuerguo999** [comment]
也可以用这种方式，找到一个之后不会继续向内遍历

https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIDGSIDOcABAIbEC8xwppm1t9AjAL4A0xARvQEwshsQAdyQAnANbJ0WEADMYEHHDD5icUaUKyxAWwAUssABs0ASQjaOpKGA5Ioy-AQCU1ADoRixPIRIASSjIbADoAcyRwvHQPLx8iYgIkGFEcNEDDE3NtYMTk1JjiAHpC4kAKdUBN+MAZxMAV+MA9tUADeUB8V0AEI0AQt0BjuUBADwLRNDhkzz89XJS0Z2DDCBQ9AAMaOmI-AH0-FhmOYGJ0NCh6AHIIPeIWcZMIULgACw8WDwFwaHgAGU1QmTgATyg0AhxRMAc90upAIAAVenBlGhRFh1DA0II8DooKRegB5eCwOCw0TwlhAA
