### ISSUE TITLE
格式化参数：isPretty 仅对js有效吗？

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#60]
经测试，对js有效，但对vue/html无效，没有缩进显示。

建议完善格式化。

复现链接：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8A3MNAdwD4AdCfQ0uNAZzhwHoDjzKXr2QAaEIpACcA1snRYQAMxgQAxnDBIIAAjiCAhhDqShAWwAUksABs0ASQg6ey9VDDWkUBUroBKZcArLlsl3GUAJMoAvDZ2AHQA5kjRvuhePn7KdEgwgrJoIcpGphY64SlpGQlMTMqAFOqAm-GAM4mAK-GAe2qABvKA+K6ACEaAIW6Ax3KAgB4JgmhwaSoB+oXpaNbAylDqgnRoAPJOilqYHsrGmpEw6pFoawDkABZwusYHygC+V65RaBBoGrT6nireymB0AAr9cHAAnms1DAJglLq4KJcKLxwNB4AAZLYSE5nGFHdTfX4KR5YSTqYzzPi+XQzfoLeCwOBYYFoS5AA

**Comment by shuerguo999** [comment]
目前是的，后续会增加html的prettier
