### ISSUE TITLE
ggc怎么可以快速获取某一个指定类型的父级呢？

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#62]
比如获取CallExpression的父级元素，在babel可以这样写：
var parentPath = path.findParent(parent => parent.isCallExpression())

在ggc里面，就不知道怎么获取了，本来想着这么做：
var result = item.parents().find(obj => obj.nodePath.name === ""VariableDeclarator"")
（ps：参考代码未调通）

却发现，居然找到的第一个父级的name是2，是个数字2，再往上的父级都有名，它是不配有名咯？

地址：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIBuBDAJwAI40BnOIgXiIB0QALNAG2aXoBoii8AjAY2pEAjAG4QHEAHckBANbJ0WEADMYEfnDBIIJAnghkVsgLYAKFWGZoAkhGNc8UMFyRQtOsgEoiwWrqJ+T0oAEiEnMAA6AHMkWKD0f24gw0oyJBgCfjQhS2s7Y0j0zOykogB6cqJACnVATfjAGcTAFfjAPbVAA3lAfFdABCNAELdAY7lAQA8ygjQ4TN0Qs2KstC8y7kjLCBQzAHI+fhXZgPm0PH4GC3VNbV0zMFITHz9t7kDPJGtItmizi8ioQjQIODIzLy3bkQAL4A26RAhIJBwP5zIgxL5ofSkMzAIhgMgABWGcDgAE9MHoYDkQf4gf4JOBoPAADIGaLKABWeHwZH4BDA7gpDDwmOxWkRWBUeGYZDQkiCJg+wwA8vBYHAsHACESgUA

请查看控制台！看看第一个父级是啥~

最后，其实上面的方式我觉得是比较可行的。而如果判断nodePath的类型的话，那就太麻烦了，毕竟有的有type，有的是数组无type，无奈~~~

最后的最后，还是**希望官方能出一个方便的获取指定类型父级的函数**。现在的parents基本不能用，我还不如递归parentPath呢。。。

**Comment by zhangdaren** [comment]
上面说有点问题，应该是要判断node，而不是value，

于是我写出来了，对比一个babel的代码仍然还是不够简洁，可能是我技术还太差了（用递归可能也还能少两行）

https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIBuBDAJwAI40BnOIgXiIB0QALNAG2aXoBoi8AjAY2pEAjAG4QHEAHckBANbJ0WEADMYEPnDBIIJAnghllMgLYAKZWGZoAkhCNc8UMFyRRN2sgEoiwWjqJ8HpQAJIKOYAB0AOZIMYHofkQBQURkSDAEfGiCFla2RhFpGVmJRAD0ZUSAFOqAm-GAM4mAK-GAe2qABvKA+K6ACEaAIW6Ax3KAgB6lBGhwGTrBpkWZaJ6lSREWECimAOS8fMsz-nNoeHwM5moaWjqmYKTG3r5bSUT4xFCEaBBwZIJnaMYRD0PPZKabsxud24BGINAAgqC8ABPeYEJBmb5PF6bG5AwhEIZkGDMSg0QgEeaQJaqdTuE5IHgAK0ugLRQxGBBOdLRREpVIiEFQaAACng4AxOdyiAAyEUstHsoXoPkC6VoCJwaFQbJUNVEZYANUIYF4VgAImg+MxCPyZMsJURUayAL4A65JQIGJBWCJsKKmeiAPyNAAxKgDNVAB+gDYnQDlfoBvH0A0eqALjltQRdTwDUaTXo4DIuoB6M0AWP+cTHkHFwa1JO2AiLwpBwf4lqJPNAptCmYBEMBkHkMpWYXQwbLFiA2vx+UlHbREatwPk-F7-Hx9iDicDQeAAGX0USUVLw+DIfDjbjnDDwLbbYFrWGUeGYZDQEkCxiRAHl4LA4Fg4AQuzagA


然后又来了问题，我想把abc=1这个表达式删除，从这行代码里面删除怎么弄？

**Comment by shuerguo999** [comment]
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIBuBDAJwAI40BnOIgXiIB0QALNAG2aXoBoi8AjAY2pEAjAG4QHEAHckBANbJ0WEADMYEPnDBIIJAnghllMgLYAKZWGZoAkhCNc8UMFyRRN2sgEoiwWjqJ8HpQAJIKOYAB0AOZIMYHofkQBQURkSDAEfGiCFla2RhFpGVmJRAD0ZUSAFOqAm-GAM4mAK-GAe2qABvKA+K6ACEaAIW6Ax3KAgB6lVpQE5NSJwaZFmWiepUkRFhAopgDkvHwrs-7zaHh8DOZqGlo6pmCkxt6+20lE52jGEVCEaBBwZKaeEbv7ps8jb2oAD4fHNbkkwMoiH8Xm8IhBUNkAGRIoj-V5weGIiJwACeUGyVBoKwAaoQwLwrAARNB8ZiEPBwGSbUE3cFJdFwkbGJA4NCfMHggC+gqIQq2woltwiBCQSDgApu0VeaD0pFMwDuZAACiM4HjMLoYNlxX4wXqMjoRmQ-CKIOJwNB4AAZfRRJQAKzw+DIfAIYDcDoYeB1es0qqwyjwzDIaAkgWM6IA8vBYHAsHACMahUA
