### ISSUE TITLE
匹配「字符串模板」的问题，会丢失内容

### ISSUE THREAD

**Issue by wztscau** [thx/gogocode#63]
```
$('`/aa/bb/${cc}`')
  .find('`$_$`')
  .each(item => {
    console.log(`value`, item.match[0][0].value)
  })
```
这个 value 会丢失 ${cc}，变成 \`/aa/bb/\`

**Comment by shuerguo999** [comment]
模板字符串需要按如下方式匹配
![image](https://user-images.githubusercontent.com/8147254/128338400-d47e4de3-664f-4e7d-9b96-b9c439533807.png)

**Comment by yaruiyang** [comment]
`请输入阶段${index + 1}阶段名称` 模板字符串想获取${index + 1}，执行  .find('\${$_$1}') 匹配不到，报  错误：Error: parse error!Missing semicolon. (1:23)
