### ISSUE TITLE
当文件名为“LICENSE”时，会被输出成文件夹

### ISSUE THREAD

**Issue by yangmi0829** [thx/gogocode#65]

**Comment by wudi3** [comment]
这个名为“LICENSE”的文件后缀名是什么？

**Comment by yangmi0829** [comment]
没有后缀






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月6日(星期五) 下午5:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thx/gogocode] 当文件名为“LICENSE”时，会被输出成文件夹 (#65)





 
这个名为“LICENSE”的文件后缀名是什么？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wudi3** [comment]
npm install -g gogocode-cli 
重新安装gogocode-cli
然后再执行转换命令试试吧。

**Comment by wudi3** [comment]
bug fixed

**Comment by linkun12345** [comment]
.
