### ISSUE TITLE
对slot转换有问题,引起报错. slot值取错了 取到最后一个属性的值的了,  所有的slot都是如此

### ISSUE THREAD

**Issue by q447643445** [thx/gogocode#66]
转换前
![image](https://user-images.githubusercontent.com/19341509/129181951-bc0f7715-9d6b-4789-bcd5-4917c9809e51.png)

转换后
![image](https://user-images.githubusercontent.com/19341509/129181837-c8a09c84-7380-40e0-ba58-bc0b699c7718.png)

**Comment by q447643445** [comment]
改了下 代码, 已经解决
![image](https://user-images.githubusercontent.com/19341509/129186514-4aa20885-f16e-4860-8ee2-d8567b5ddf6c.png)

**Comment by eyis** [comment]
thx
