### ISSUE TITLE
import Vue from "vue"; 变成了 import * as Vue from 'vue'

### ISSUE THREAD

**Issue by Trinidad233** [thx/gogocode#68]
import Vue from "vue"; 变成了 import * as Vue from 'vue'
这样会把全部的模块引入吗？岂不是很占容量

**Comment by wudi3** [comment]
这样` import { createApp } from "vue";`写的话，`createApp` 方法可能与现有代码中的 `createApp`方法名称重复。改成`Vue.createApp`可避免这种情况出现。
如果你的代码里面没有`createApp`，Vue的引用可以写成这样：` import { createApp } from "vue";`

**Comment by wudi3** [comment]
close
