### ISSUE TITLE
匹配return $_$return，match["retrun"]出现其他数据

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#71]
这条我不太好判断是否应该如此，还是设计如此，

比如代码：
`function xx(){
  var a = 1;
  return 666
}
`

使用选择器：`'function $_$xx(){return $_$return}'`后，
在match里得到两条数据： `var a=1` 和 `return 666` ，而本意是只需要 `return 666` 这条数据。
是否设计如此还是？

地址：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIBuBDAJwAI44iBeEgCzAGcAaIvCogRgG4AdCbgMxggBjOGCQQiADwkAKAJTBuRJUXzFm5AKxdxygmjgwC4gGynj3AL4h6IAO5ICAa2TosIfkJFiSBPBFq8DgC20rxgADZoAJIQgYx4UGCMSFBe-rJECjqCYrRkACQsCWAAdADmSBU56IpEOf5ktEiGgmgsYZExgSVNLWi1APQDRIAU6oCb8YAziYAr8YB7aoAG8oD4roAIRoAhboDHcoCAHrV6BkZE+dK9BK2ytUolYRAo0gDaZ8oA5Kr7APr5cDS0AHJ4QW2UHzoD3o9yUDw8wlE4nybykcmAO0M0LeiKMFmB9wAuqcdOc0HhBFRQgJId5pGA4GgghkssplPUmpESuFKuTKdT7hYcXTymgIGhfJS5JZuNZwNB4AAZPxlNxwACeUDQtEEBDAqTFVDwtAACjsRAKsHACDA0DYckEoIQ0AB5eCwOBGk1oCxAA

**Comment by shuerguo999** [comment]
1.0.40 fix
