### ISSUE TITLE
连锁反应：替换表达式时，如果变量在缩写变量声明里时会误操作

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#72]
比如代码:
`var a=5, b=6`

代码： `replace("var a=5", "就这样了")`

替换后，只剩下："就这样了"， 实际应该是留下var b = 6

地址：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIBuBDAJwAI8BeAVgBoiAjUgNhEpAHckCBrZdLEAMxgQAxnDBIIROATwQAzn3YBbABR8wAGzQBJCAup4oYakiijxsgJRFgAHQlEh5uEQAkRUiUMA6AOZI-juh2RA5ORLJIMARCaO5Eapo6Cl4RUTHBRAD0mUSAFOqAm-GAM4mAK-GAe2qABvKA+K6ACEaAIW6Ax3KAgB4ZBGhwURIuyqnRaBZerVDqeDHKAOT4xHhx5GPUY4CMOvmA7BaAYXJj-T5oEGjScGjKFnYAvnZM4NDwADIyPrxwAJ5QaLJCBGCm5wAWeLIACq04KJdlgpDA0MxHIooIQ0AB5eCwOCggjg45AA

**Comment by zhangdaren** [comment]
> 估计gogocode不支持这种缩写的变量声明

哈哈哈，自信点，把“估计”去掉，还有那种带逗号的代码表达式。

**Comment by shuerguo999** [comment]
find('var a = 5')匹配到的是整个VariableDeclaration所以replace结果是符合预期的，这里建议find之后replaceBy
![image](https://user-images.githubusercontent.com/8147254/141273947-13328c43-f905-4eff-b4e5-e4b18d9e4aa1.png)
