### ISSUE TITLE
可以把各语言的generate()函数暴露到api里自由调用嘛

### ISSUE THREAD

**Issue by quanxiaole** [thx/gogocode#73]
希望做到能够修改vue template的AST树，再集成回代码，而不是使用下面官网中模板替换的方式

```
templateAst
  .replace(`<el-popover open-delay="$_$" $$$1>$$$2</el-popover>`, `<el-popover show-after="$_$" $$$1>$$$2</el-popover>`)
  .find('<$_$><$_$>')
  ......
```

**Comment by shuerguo999** [comment]
$(code, { parseOptions: { language: 'vue'})
.find(<template></template>)
可以取到template的AST，对其进行操作就可以改变原ast，操作之后generate会打印template代码，如果先调用root()再generate()可以打印完整的vue sfc代码

**Comment by quanxiaole** [comment]
明白啦 谢谢
