### ISSUE TITLE
对html进行替换时，如果content里含小于号时，会替换出有问题的代码

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#77]
比如：
`<dd>1<5</dd>
<view>我是打酱油</view>`

我想将`<dd>1<5</dd>`替换为 `<dd test="zpzpzpzp">1<5</dd>`，

结果变成：
`<dd test="zpzpzpzp">1
<5<>
<view>我是打酱油</view></5<></dd>`
与预期不符！

应该是对<的解析有点点问题，其实吧，htmlparse2也有这毛病，希望大佬们可以尽快解决，感谢~

复现：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8KUB8AjDgKw4D0+BAOhDgG5hoDuBgiEaD0ZoMpGgjomCdNpSasCIADQgWSAE4BrZOiwgAZjAgBjOGCQQABHGkBDCAGdlMgLYAKZWAA2aAJIRzY3Yahg3SKFp0mASl1gOl1ddX84XQASXQBed08AOgBzJDSI9FDwyN0TJBhpdTR43VsHZ3Mk-MLi7IoKXUAKdUBN+MAZxMAV+MA9tUADeUB8V0AEI0AQt0BjuUBAD2zpNDhCvWirGqK0N2BdKENpEzQAeV9tU0xg3TtjFJhDFLRDgHIACzgLO2vdAF9XgOywpKmoE+KrT5hXQAAzwKBi0WiRAIkOiACZKNRgWJAWFQfh9GgTHA4jQQAAvKCE4lQPEQqEwyEIqiEYGAj56IGpNAQNBGOBoKwMl50cTgaDwAAypyU90efNuhhMAAUpnAtGysAYYMsQBELOsptt4LA4ErpCqXkA

**Comment by shuerguo999** [comment]
gogocode@1.0.32 fixed
