### ISSUE TITLE
对html/vue的template进行连续替换时，出现异常情况，替换不完全！

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#78]
有代码：
`<div>   

	<block class="zpzp" data-id="zpid" >我是内容</block>   

	<block class="zp" data-id="zpid" >我也是内容</block>   

    <block class="zp" data-id="zpid" >打酱油的来了</block>   
</div>`

想把标题里面的class属性和data-id属性去除，我使用把属性遍历出来，然后再删除，却未能删除，原因暂无时间去追查。。

而我直接进行replace时，发现：如果只替换一个属性，是完全没问题，但连续替换属性时就出问题了！
代码为：
`
$(source, { parseOptions: { language: 'html' } })   
    .replace(   
      '<$_$1 class="$_$2" $$$1>$$$2</$_$1>',   
      '<$_$1 $$$1>$$$2</$_$1>'   
    )   
    .replace(   
      '<$_$1 data-id="$_$2" $$$1>$$$2</$_$1>',   
      '<$_$1 $$$1>$$$2</$_$1>'   
    )   
    .generate()   
`
替换结果为：
`
<div>

    <block>我是内容</block>

    <block data-id="zpid">我也是内容</block>

    <block data-id="zpid">打酱油的来了</block>
</div>
  

`
只替换一个属性是完全没得问题的：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8KwBuAfADoRklw4BGANkgMYDWABA7QIYDOXAvCSABeUYQJYoOcDgFowKfkKhyBRQIhGgejNAoYqBO7RwB6Ooyaly5KoeZtOPBaJDjJMubaUoVqwPpyW3QfrMTZCxBLDR+rOzcfAJ2DlKy8tGuKoDKRoCOiYCdNoAhboCm5oBhcvoWxmT6+MQgADQgAO5IAE5MyOhYIABmMBAMcGBIECxwtRwQXC11ALYAFC1gtGgAkhAj5SwcSktIUF09XACULMCBbFtwLAAkLLzLSgB0AOZIdwyoaAePQ8dcSDC1DGjnLFMzeYjK4fL4-A56PQsQAU6oBN+MAM4mAFfjAHtqgAN5QD4roAEI0ygGO5QCAHgdamg4F9eidxqDvmglsAWFAOLUuGgAPIbbpDTB7FicCA3GAcG5oTkAcgAFnBRrRhSwAL6y7YHIJXIlQTg-caK4LCnAnAD6JwAjFZIgo9ScAExiE7Wg1Ea0W-Rm23C8qaoLap2nG1263mx3652ahWmYIsW5oCBoAZwNDjYMysgVcDQeAAGUGN2a4slSdF3AACkS4F0o1h+jBqSBHqN6UTmfBYHAy7UKzKgA

重现地址：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8KwBuAfADoRklw4BGANkgMYDWABA7QIYDOXAvCSABeUYQJYoOcDgFowKfkKhyBRQIhGgejNAoYqBO7RwB6Ooyaly5KoeZtOPBaJDjJMubaUoVqwPpyW3QfrMTZCxBLDR+rOzcfAJ2DlKy8tGuKoDKRoCOiYCdNoAhboCm5oBhcvoWxmT6+MQgADQgAO5IAE5MyOhYIABmMBAMcGBIECxwtRwQXC11ALYAFC1gtGgAkhAj5SwcSktIUF09XACULMCBbFtwLAAkLLzLSgB0AOZIdwyoaAePQ8dcSDC1DGjnLFMzeYjK4fL4-A56PQsQAU6oBN+MAM4mAFfjAHtqgAN5QD4roAEI0ygGO5QCAHgdamg4F9eidxqDvmglsAWFAOLUuGgAPIbbpDTB7FicCA3GAcG5oTkAcgAFnBRrRhSwAL6y7YHIJXIlQTg-caK4LCnAnAD6JwAjFZIgo9ScAExiE7Wg1Ea0W-Rm23C8qaoLap2nG1263mx3652ahW9YLKtCqjjqt0sD0B2JOBIgM2W+z2232v16J1EF3R2OGr2Gn0OrMBnNBzW3NAQNADOBocbBmVkCrgaDwAAygxuzXFktbou4AAUiXAurWsP0YNSQI9RvSicz4LA4JPatOZUA

**Comment by zhangdaren** [comment]
经过调试源代码，
发现是src/html-core/core.js里面51行：
`
 res.nodePathList.forEach((p, i) => {
                let posStr = '';
                if (p.node.content.openStart) {
                    posStr = `${p.node.content.openStart.startPosition},${p.node.content.openEnd.endPosition}`;
                } else if (p.node.content.value) {
                    posStr = `${p.node.content.value.startPosition},${p.node.content.value.endPosition}`;
                }
                 if (posStrList.indexOf(posStr) == -1) {
                    // 去重
                    nodePathList.push(p);
                    matchWildCardList.push(res.matchWildCardList[i]);
                    posStrList.push(posStr);
                 }
            });`

与这个`  if (posStrList.indexOf(posStr) == -1) {`判断有关。

如果被替换的标签，都是同样的标签属性，那么在搜索时，
p.node.content.value.startPosition和p.node.content.value.endPosition
在标签上面的值是一样的，那么，经过这个判断，就只会有第一个被搜索到，导致替换不完全。。

具体为啥导致这个问题，去掉这个判断可行不（未知这个判断的作用），还待官方大佬修复吧。

PS：经测，去掉这个判断，可以全部替换。

**Comment by shuerguo999** [comment]
gogocode@1.0.32 fixed
