### ISSUE TITLE
template里面注释的代码在replace也被替换了

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#80]
rt，这算正常操作还是不正常操作？

地址：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8KwBuABAMYA2AhgM5UC8AOiBYwHwCMOA9PgS-RHkKlKNBk1YAmLjz4CAhAFoFRHATBoA7iwAqAUQDK2rms0siS2SAA0IDUgBOAa2TosIAGYwIJOGCQQiOHsKCCp3BwBbAAp3MDI0AEkIcKsiCigwVKQoX38qAEoiYH4iUjy4IgASIlo0jIA6AHMkZpJUNBKy0IqqJBh7EjQaolj4pPD63v7BzrbutKoK2sqoqYG0VOAiKAp7KjQAeRy-UMwiokoIRpgKRrQzgHIACzgIsgeiAF8v-M7qOHq9jQUEogyiD1U6i0xihLAeqQhMkA+nKAf7NAEbGgDC5QDYaoB8f8A6d6AY2tABx6gFg5HHSQhw34BIicThEIFwfoBACefXsgWCoXC9giaBQZXQRCeaCBnUZzIWALuEFFFDgaCi1M+-Gs4Gg8AAMiFGm4Xm81U9qAAFRm+UVYIIwDYgNoRHZAg7wWBwS32a2fIA

**Comment by shuerguo999** [comment]
fix
