### ISSUE TITLE
解析<div v-if="a<1"></div>报错！

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#81]
rt。标签属性里面含<时，解析不正常！

地址：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8c0C2UANgIb4B8AOhAAS04pgButzAtGAGYC8VIpHAEZ+FITgD0TZtToNptAMZkAzir4DRAJknTZk-ETKUaNHCsUAnMFDizFSCCri1StHrREQHTlwCN3Wi0zCQtrW1kQABoQAHckSwBrZHQsEC4YbzgwR1o4S1InLgSCAAouMGI0AEkIYqjXKDAGpFscpwBKWmAaeh9nWgASQNImgDoAcyQph3RepUcBlSQYS0U0QIqq2uKx5dX1+f6XUgGPQdL9tbQG4FooUksVNAB5NsXMbtoyCAmYUgmaE+AHJmDA0MDaABfaEdI6LFyGEjkDYeU5wMYVCAoUrAvCEZGUAwE4xoCjAuFyJGksaWNDI9a4xgsJSqdT8UiiQYAfUGuhY5IaeL0PL5UgFFPhvloYRsLjRzkxkBxeNlEUkarskrkmtp9LIjOBx1cgVFwKFxrcHi0FMmaAgaAK+FKlPoEgktDpcFWdAAnitLHkCkUSmgUAt0LQABaOtDzL0+1yKwEOp1oF00KE0aLgaDwAAyhQmaTBGBiUdOAAUvdlHVh8uCYg4iI9XvBYHB65ZwVCgA

**Comment by shuerguo999** [comment]
已修复，感谢
