### ISSUE TITLE
replace时，使用具名进行替换可以，但使用通配符不行！

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#82]
有代码：
`call((o={a:1},bb,cc,o))`
想转换为：
`call({ a: 1, bb, cc })`

使用
` .replace('call((o={$$$1},$$$2,o))', 'call({$$$1, $$$2})')  //这个行`
是没问题的

但使用：
`  .replace('call(($_$1={$$$1},$$$2,$_$1))', 'call({$$$1, $$$2})')`
就不行了，输出：`call({ a: 1 })`
可以发现bb和cc都被删除了。。。

但实际操作中，应该是使用通配符，不然就很难搞咯~

使用具名是ok的：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA6EBuAhgE4AEARuQDQDGNpAvKQIwDceRZSjpwAvnkEQahADaiAFBKQNghTMz5VKtGlSQBKDSCogA7kmIBrZOiwgAZjGFwwSCKTjFCEAM4XDAWwkWwotACSEB5UpIRQYKFIULb2rhq8eKSkNHFwpAAkPOFgAHQA5kiFqehJKWmkrkgwxDRoPL7+QR65VTV1ZQD0naSAFOqAm-GAM4mAK-GAe2qABvKA+K6ACEaAIW6Ax3KAgB5lxGhwNQ4ZEm21aBpluatQooR1EgDkIuJSMsAZ94pU9xkATOpa56GXYpJ3D6HPF58DTnBKkbr9QBUcoAZCK6PUOaGOpzQFyukgkGQA+hlmLJno9AU9scwPl80RI-jiAfcgSCwRDIYBYOVhDlIBTQEDQzjgKP2EAEEB04Gg8AAMi58uY4ABPKBoVw0YhgGJCgAWhFcAAVVnBbFysE4YGhdKlPFASGgAPLwWBwA3EI18IA

而使用通配符不ok：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA6EBuAhgE4AEARuQDQDGNpAvKQIwDceRZSjpwAvnkEQahADaiAFBKQNghTMz5VKtGlSQBKDSCogA7kmIBrZOiwgAZjGFwwSCKTjFCEAM4XDAWwkWwotACSEB5UpIRQYKFIULb2rhq8eKSkNHFwpAAkPOFgAHQA5kiFqehJKWmkrkgwxDRoPL7+QR65VTV1ZQD0naSAFOqAm-GAM4mAK-GAe2qABvKA+K6ACEaAIW6Ax3KAgB5lxGhwNQ4ZEm21aBpdPbmrUKKEdRIA5CLiUjLAGQ+KVA8ZAEzqWhehV2KS94+hF6vPgaC4JUjdfqAKjlADIRZSOaBOZzQl2ukgkGQA+hlmLIXk8gc9scxPt80RJ-jjAQ9gaDwZCoYBYORhgBh-yiAGJU6IBfhMA1RGAAiVACZpgDC5eH5NAQNDOOAo-YQAQQHTgaDwAAyLny5jgAE8oGhXDRiGAYoqABaEVwABVWcFskqwThgaF0qU8UBIaAA8vBYHB7cRHXwgA

**Comment by shuerguo999** [comment]
可以先把变量名取出来，再replace

https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA6EBuAhgE4AEARuQDQDGNpAvKQIwDceRZSjpwAvnkEQahADaiAFBKQNghTMz5VKtGlSQBKDSCogA7kmIBrZOiwgAZjGFwwSCKTjFCEAM4XDAWwkWwotACSEB5UpIRQYKFIULb2rhq8eKSkNHFwpAAkPOFgAHQA5kiFqehJKWmkrkgwxDRoPL7+QR65VTV1ZQD0naSAFOqAm-GAM4mAK-GAe2qABvKA+K6ACEaAIW6Ax3KAgB5l-umcAHKEnvVMGRJttWgaub4QKBIABiLiUhkA+hnMshkviqEvGQBMWhfHnoRwGgACwA2swALoggAM4NyRFEMDQQjKxDQcBqDj2BzqGjKyVyqKgokIdQkeOSpCuYkkEgywA2WzQfGeryUH0+VDpDO2fB+VHJyQA5NdJMAPsx3i9PrzBeSEt1+oAqOUAsHKAGQjADD-lEAMSp0QC-CYBqiMABEqAEzTAGFy5IKaAgaGccDQElxEAEEB04Gg8AAMi58uY4ABPKBoVw0YhgGKuoGEVwABVRcFsNqwTkRulSnigJDQAHl4LA4EniIi+EA
