### ISSUE TITLE
使用before和after添加注释时，顺序错乱。

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#86]
如示例：

示例一：使用before或after给某行代码添加代码是没问题的
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcI4AsCGcAdAGYwQAUA5HGgM5xUCUAOhCADQgDuSATgGtk6LCDIQAxnDBIIAAjh98EOiX4BbCiTAAbNAEkIajnPxQwJpFGmy6TOcDZy5E23DkASOQF5T5ogDmSEGu6E4ubnJ0SDB8Emg+ctp6hmpE0bHx4QD02XJ8aHCx8gCeMXwKSipqfOpoKBHocrhoBeEFRXzyHhQZcWhMpJAo1HiEpOQUHgD6HkzMRABGaDVoFCwgAG74FcuriQCsANwbg-gktHzrWzumF62JAGynRHxISHAUgwFoEK2Ea1YEAAvmxOOBoPAADLKAKiOAlKD0CR8MDWcEEOgABQ60laWEUMDQXFc6igOzQAHl4LA4AS+ETgUA

示例二：使用before或after给 `var a = 1` 上下添加注释也是没问题的
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIBuBDAJwAI40BnOIgXiIEYAdCEAGhAHckCBrZdLEAGYwIAYzhgkEEgTwQyAzgFsAFALAAbNAEkIC5kTxQw+pFHGSyASiLBGRIiIuUAJNQNGAdAHMkPx+jsHJyIyJBgCETQ3NU0dBQ9Q8MjAgHoUogI0OHCpAE8w4jgZOQUCRTQUIPQiAAs0TMDM7IIpZ2VEiLRLDzUIFGUAcnxC8koaWgHugCM0UrRlehB6RjSZueWIRe68AVICBaWVlJ29ja2PAiQkOGVurzQIerxSW8YAX0YWcGh4ABlZLz8OC5KDkEQEMBmL41PBkAAKTXE9SwRRgaFYjkUUEIaAA8vBYHAUQQ0W8gA

示例三：使用before或after给 `this.fun()` 上下添加注释就有问题啦~！~~~
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcI4AsCGcAdAGYwQAUA5HGgM5xUCUAOhCADQgDuSATgGtk6LCDIQAxnDBIIAAjh98EOiX4BbCiTAAbNAEkIajnPxQwJpFGmy6TOcDZy5E23DkASOQF5T5ogDmSEGu6E4ubnJ0SDB8Emg+ctp6hmpE0bHx4QD02XJ8aHCx8gCeMXwKSipqfOpoKBHocrhoBeEFRXzyHhQZcWhMpJAo1HiEpOQUHgD6HkzMRABGaDVoFCwgLGy5y6tbEBuD+CS0fOub29nHp-uHRHxISHAUgwFoEK2Ea6wQAL5snHA0HgABllAFRHASlB6BI+GBrICCHQAAodaStLCKGBoLiudRQfAFADy8FgcCxfBxvyAA

**Comment by shuerguo999** [comment]
callExpression节点的注释位置比较特殊，可以使用这个方法：（parent支持根据特定属性筛选啦！）https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcI4AsCGcAdAGYwQAUA5HGgM5xUCUAOhCADQgDuSATgGtk6LCDIQAxnDBIIAAjh98EOiX4BbCiTAAbNAEkIajnPxQwJpFGmy6TOcDZy5E23DkASOQF5T5ogDmSEGu6E4ubnJ0SDB8Emg+ctp6hmpE0bHx4QD02XJ8aHCx8gCeMXwKSipqfOpoKBHocrhoBeEFRXzyHhQZcWis8s5ypJAo1HiEpOQUHgD6HkzM4c5EUPgFEHAUwAolUGiYclQAogAeUAV0dDIQAMpwhGh1W1RyAL6DwyMARmg1aGoLDYuT+AOBEGWQ1W+BItD4QJB2Vh8IhUO+RD4SCQ2y+w0CaAgrSeFEG7zYnHA0HgABllAFRHB9vQJHwwNZKQQ6AAFDrSVpYRQwNBcVzqdYFADy8FgcEFfGFXDoMB+ADUwGhuAAVZmMgoYd5AA
