### ISSUE TITLE
有没有支持css转换的方法或者工具

### ISSUE THREAD

**Issue by Fuphoenixes** [thx/gogocode#94]
- version:
- playground demo:
- your description:

**Comment by zhangdaren** [comment]
const postcss = require('postcss')
const lessSyntax = require('postcss-less')
const ScssSyntax = require('postcss-scss')

css  用  postcss
less 用  postcss-less
scss 用  postcss-scss

**Comment by ediaos** [comment]
> const postcss = require('postcss') const lessSyntax = require('postcss-less') const ScssSyntax = require('postcss-scss')
> 
> css 用 postcss less 用 postcss-less scss 用 postcss-scss

请问下如何使用？plugin

**Comment by zhangdaren** [comment]
> > const postcss = require('postcss') const lessSyntax = require('postcss-less') const ScssSyntax = require('postcss-scss')
> > css 用 postcss less 用 postcss-less scss 用 postcss-scss
> 
> 请问下如何使用？plugin

我把gogocode当成一个npm库，然后需要使用到gogocode就使用它进行解析，需要解析css就引入上述库进行解析 

至于v2->v3的那个工具的话，要么你使用它先转换，然后再自己使用gogocode+postcss进行针对性处理 

要么就自己对v2->v3工具扩展一下。

**Comment by ediaos** [comment]
> 

了解了，感谢感谢。我这边场景想要实现比如 test.less 文件 css 替换。
`
.banner{
  &__info{
    
 }
 .abc__test{

 }
}
`
想要使用 gogocode 查找或者替换如下2个class，最终文件还是 test.less，请教下你这边是否遇到过这类场景处理
1.  .banner__info 
2.  .abc__test

**Comment by zhangdaren** [comment]
> > 
> 
> 了解了，感谢感谢。我这边场景想要实现比如 test.less 文件 css 替换。 ` .banner{ &__info{
> 
> } .abc__test{
> 
> } } ` 想要使用 gogocode 查找或者替换如下2个class，最终文件还是 test.less，请教下你这边是否遇到过这类场景处理
> 
> 1. .banner__info
> 2. .abc__test

我有做过检测iconfont对应的字体是否存在的校验，单位转换等，
你这个建议直接使用postcss-less这个库，载入这个less，然后进行替换。  

经测，你这一段，使用post-less解析后的结构如下：
``` json
{
    "raws": {
        "semicolon": false,
        "after": ""
    },
    "type": "root",
    "nodes": [
        {
            "raws": {
                "before": "",
                "between": "",
                "semicolon": false,
                "after": "\n        "
            },
            "type": "rule",
            "nodes": [
                {
                    "raws": {
                        "before": "\n            ",
                        "between": "",
                        "after": ""
                    },
                    "type": "rule",
                    "nodes": [],
                    "source": {
                        "inputId": 0,
                        "start": {
                            "offset": 21,
                            "line": 2,
                            "column": 13
                        },
                        "end": {
                            "offset": 29,
                            "line": 2,
                            "column": 21
                        }
                    },
                    "selector": "&__info"
                },
                {
                    "raws": {
                        "before": "\n            ",
                        "between": "",
                        "after": ""
                    },
                    "type": "rule",
                    "nodes": [],
                    "source": {
                        "inputId": 0,
                        "start": {
                            "offset": 43,
                            "line": 3,
                            "column": 13
                        },
                        "end": {
                            "offset": 54,
                            "line": 3,
                            "column": 24
                        }
                    },
                    "selector": ".abc__test"
                }
            ],
            "source": {
                "inputId": 0,
                "start": {
                    "offset": 0,
                    "line": 1,
                    "column": 1
                },
                "end": {
                    "offset": 64,
                    "line": 4,
                    "column": 9
                }
            },
            "selector": ".banner"
        }
    ],
    "source": {
        "inputId": 0,
        "start": {
            "offset": 0,
            "line": 1,
            "column": 1
        }
    },
    "inputs": [
        {
            "hasBOM": false,
            "css": ".banner{\n            &__info{}\n            .abc__test{}\n        }",
            "id": "<input css nOY3xb>"
        }
    ]
}
```

可以看到`&__info{}` 这种拼接结构，解析为： 
``` json
"selector": "&__info"
```
需要自己拼接上一级然后再进行判断了，具体的策略是从父到子，遍历时缓存父的路径，还是怎么着，需要你自己考虑一下了。

另一个类名就很简单的了，直接就是"selector": ".abc__test"，直接替换即可。

这个工具可以看出css的结构：https://astexplorer.net/#/gist/f3b9702daff8f1c4e867a67ead1c044e/8063931fb3688ef48369ec2e6ad911e459a92ff9

测试代码：
``` js
const lessSyntax = require('postcss-less')
const ScssSyntax = require('postcss-scss')

test2()
function test2 () {

    var css = `.banner{
            &__info{}
            .abc__test{}
        }`

    var ast = lessSyntax.parse(css)
    const styleRules = ast.nodes
    console.log(JSON.stringify(ast, null, 4))
}
```

**Comment by ediaos** [comment]
> > > 
> > 
> > 
> > 了解了，感谢感谢。我这边场景想要实现比如 test.less 文件 css 替换。 ` .banner{ &__info{
> > } .abc__test{
> > } } ` 想要使用 gogocode 查找或者替换如下2个class，最终文件还是 test.less，请教下你这边是否遇到过这类场景处理
> > 
> > 1. .banner__info
> > 2. .abc__test
> 
> 我有做过检测iconfont对应的字体是否存在的校验，单位转换等， 你这个建议直接使用postcss-less这个库，载入这个less，然后进行替换。
> 
> 经测，你这一段，使用post-less解析后的结构如下：
> 
> ```json
> {
>     "raws": {
>         "semicolon": false,
>         "after": ""
>     },
>     "type": "root",
>     "nodes": [
>         {
>             "raws": {
>                 "before": "",
>                 "between": "",
>                 "semicolon": false,
>                 "after": "\n        "
>             },
>             "type": "rule",
>             "nodes": [
>                 {
>                     "raws": {
>                         "before": "\n            ",
>                         "between": "",
>                         "after": ""
>                     },
>                     "type": "rule",
>                     "nodes": [],
>                     "source": {
>                         "inputId": 0,
>                         "start": {
>                             "offset": 21,
>                             "line": 2,
>                             "column": 13
>                         },
>                         "end": {
>                             "offset": 29,
>                             "line": 2,
>                             "column": 21
>                         }
>                     },
>                     "selector": "&__info"
>                 },
>                 {
>                     "raws": {
>                         "before": "\n            ",
>                         "between": "",
>                         "after": ""
>                     },
>                     "type": "rule",
>                     "nodes": [],
>                     "source": {
>                         "inputId": 0,
>                         "start": {
>                             "offset": 43,
>                             "line": 3,
>                             "column": 13
>                         },
>                         "end": {
>                             "offset": 54,
>                             "line": 3,
>                             "column": 24
>                         }
>                     },
>                     "selector": ".abc__test"
>                 }
>             ],
>             "source": {
>                 "inputId": 0,
>                 "start": {
>                     "offset": 0,
>                     "line": 1,
>                     "column": 1
>                 },
>                 "end": {
>                     "offset": 64,
>                     "line": 4,
>                     "column": 9
>                 }
>             },
>             "selector": ".banner"
>         }
>     ],
>     "source": {
>         "inputId": 0,
>         "start": {
>             "offset": 0,
>             "line": 1,
>             "column": 1
>         }
>     },
>     "inputs": [
>         {
>             "hasBOM": false,
>             "css": ".banner{\n            &__info{}\n            .abc__test{}\n        }",
>             "id": "<input css nOY3xb>"
>         }
>     ]
> }
> ```
> 
> 可以看到`&__info{}` 这种拼接结构，解析为：
> 
> ```json
> "selector": "&__info"
> ```
> 
> 需要自己拼接上一级然后再进行判断了，具体的策略是从父到子，遍历时缓存父的路径，还是怎么着，需要你自己考虑一下了。
> 
> 另一个类名就很简单的了，直接就是"selector": ".abc__test"，直接替换即可。
> 
> 这个工具可以看出css的结构：https://astexplorer.net/#/gist/f3b9702daff8f1c4e867a67ead1c044e/8063931fb3688ef48369ec2e6ad911e459a92ff9
> 
> 测试代码：
> 
> ```js
> const lessSyntax = require('postcss-less')
> const ScssSyntax = require('postcss-scss')
> 
> test2()
> function test2 () {
> 
>     var css = `.banner{
>             &__info{}
>             .abc__test{}
>         }`
> 
>     var ast = lessSyntax.parse(css)
>     const styleRules = ast.nodes
>     console.log(JSON.stringify(ast, null, 4))
> }
> ```

👍，感谢感谢，我试试
