### ISSUE TITLE
html 转换的时候，有没有方式可以把属性值的引号去掉？

### ISSUE THREAD

**Issue by AnaniZhu** [thx/gogocode#95]
- version: 1.0.37
- playground demo: https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8KwBuAfADoQAEl5OAhgLRw0BGANmuZgMZIswC2EAM4BeEiG68BgsZSZIATunloUHFDUZ1BSGPM5pRIdYzFEcAenqNWaUhSq06TeHCQU4ATygGxUeWD4aeQ9TThYwTgBrcj40C3pnOFcIO0oLfGIQABoQAHcFSOR0LBAAMxgITjgwN3I4eRohUoU+AApSsDYASQhmrPIaKDB+pChqt0EASnJgMkpuIThyABJyYQGhgDoAcyRd7nQ58gXBJe1dfTXyDu7epE3zvTQjk6WaU6vl1sf9fuByKBBQRoADyYxqQkwM3ILEa2xgNG2aChAHIABZwPgsFHkAC+eMmR3ecE2HQgKFaKJwywA+qtacsAIzCBkAJjM5gZRBRhPsmzQNE4aNarTAcDQfGmwiIMyO8wmPDQmxYe1F4slcuOEzeSXkgiuYolm0CcCFAG1GQBdTWvcgEGi8ND69aGvjGjTm1nW+yUDT1QSkhQAUUFwrVEv6kHQAA8pTLZj6qGBSuRw277Y6Hox5HBBAB1MXClGYHnTBNUCvkV2bDMwdgu9U1h11h7hfSUxk8zUV2tOs1RtDRy1Nx1XAAGwGWwF7gn75MHw97uNxY+7eM1uN5lE3R3M5nIyjgugoHh08jqDSaLRUWvQ5DRaGUR0Px4Gpx2aAgj40aFavNxZDZOA0DwAAMnCJQYliQFou8AAKh7VI+WD1HWOTcHwgLKCC8CwHAKHyHWuJAA
- your description:
想做一个简单的功能，把 vue 的模板语法转成 jsx 语法，目前属性值替换后还有携带双引号

![image](https://user-images.githubusercontent.com/26708304/139205493-4c772fa0-6613-4696-a6e8-3da4fb06e935.png)

**Comment by shuerguo999** [comment]
1.0.39已支持
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8KwBuAfADoQAEl5OAhgLRw0BGANmuZgMZIswC2EAM4BeEiG68BgsZSZIATunloUHFDUZ1BSGPM5pRIdYzFEcAenqNWaUhSq06TeHCQU4ATygGxUeWD4aeQ9TThYwTgBrcj40C3pnOFcIO0oLfGIQABoQAHcFSOR0LBAAMxgITjgwN3I4eRohUoU+AApSsDYASQhmrPIaKDB+pChqt0EASnJgMkpuIThyABJyYQGhgDoAcyRd7nQ58gXBJe1dfTXyDu7epE3zvTQjk6WaU6vl1sf9fuByKBBQRoADyYxqQkwM3ILEa2xgNG2aChAHIABZwPgsFHkAC+eMmR3ecE2HQgKFaKJwywA+qtacsAIzCBkAJjM5gZRBRk02aBonDRrVaYDgaD402ERBmR3mEzeSXkgiuovFmw09UpCzFEBJGv8iTQgh5soGisEpIUAFEBULWvr+pB0AAPSXS2b2KjkMClcitU1e-WbSJoDzkABk4YDVCDIY8m21aF1Eajnq9ZvqwdDCbcOpJpyCcEEAHVRUKUZgTWnKNMPemY4qs-HE8n1rHsy38+F9JTGVX65QgwX5HBiw0oN55DndUmlusUcAUdHB42kygx4NJ9O81cUbil9W8abcYT7CejuZzORlHBdBQPDp5HUGk0Wipjqh2Gi0Mojje7wMpw7EmP4aGgrSnriZDZOA0DwAAMnCJQYliMFou8AAKN7VD+WD1DAaA5NwfCAsoILwLAcB4fIBE5IIMBMAAamAaC5AAKl4GDYMRpEYLiQA
