### ISSUE TITLE
Bug Report From Playground: 获取script标签时，match为undefined

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#98]
- version: 1.0.37
- playground demo: [link](https://play.gogocode.io/?v=1.0.37#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8BnAYwCcwo4ACAQzjiIF4AdEAVifJWssZAEYAGNgD4cAekIkyg8iAA0IAO5IiAa2TosIAGYwIBOGCQRytShDyalAWwAUmsABs0ASQgWZVKGHdIyBswEpyYAYjcgJDPAoAEnI6DzAAOgBzJBTw9BDyMIiKPCQYIgI0WPI7RxcLBLyCoszsswpKSJKo62rCtHdgcihKIjw0AHlfCMwg8ntTJJhKJLQxgHIACzhLewXyAF8t-xC6kRFyIjQ4AqMAT3yiYyJTcys0FGz0ciW0Y7rj06IjJrg6rIJOwQFDWAAG+GIpEaNHoTCiAH0ojw2FE0TxBGiogAmUTiaGCMG7UKAtCUAhLWw6PR+cjWMBwNCWQLBElZep5RwJeypawLBlMhbuAXMgE7BJEJBIODWYns8jJNAQd7UNCykKbEKycDQeAAGSmGhWa21SyaAAUvvp3lhaDBOiBwpZesdBvBYHBbUR7ZsgA)
- detail desc:

用div标签，又可以获取到match：
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8BnAYwCcwo4ACAQzjiIF4AdEAVifJWssZAEYAGNgD4cAekIkyg8iAA0IAO5IiAa2TosIAGYwIBOGCQRytShDyalAWwAUmsABs0ASQgWZVKGHdIyBswEpyYAYjcgJDPAoAEnI6DzAAOgBzJBTw9BDyMIiKPCQYIgI0WPI7RxcLBLyCoszsswpKSJKo62rCtHdgcihKIjw0AHlfCMwg8ntTJJhKJLQxgHIACzhLewXyAF8t-xC6kRFyIjQ4AqMAT3yiYyJTcys0FGz0ciW0Y7rj06IjJrg6rIJOwQFDWAAG+GIpEaNHoTCiAH0ojw2FE0TxBGiogAmUTiaGCMG7UKAtCUAhLWw6PR+cjWMBwNCWQLBElZep5RwJeypawLBlMhbuAXMgE7BJEJBIODWYns8jJNAQd7UNCykKbEKycDQeAAGSmGhWa21SyaAAUvvp3lhaDBOiBwpZesdBvBYHBbUR7ZsgA

**Comment by shuerguo999** [comment]
1.0.38 fix
https://play.gogocode.io/#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8BnAYwCcwo4ACAQzjiIF4AdEAVifJWssZAEYAGNgD4GEcmPIA3SkSrk65HgG4R4ydPIAjOQpE4A9IRJlhEfMVIVqtbgDYhK8VJlb5PXQfPHyIADQgA7khEANbI6FggAGYwEARwYEiitJQQeJFBALYAFJFgADZoAJIQ6T5UUGBlSGQJqQCU5MAOBIl4FAAk2pQVAHQA5kgDLejNrRR4SDBEBGjauQXF6T0TUzOjqZZt2u1ZK9NoZcDkUNJ4aADyNa2YjeR5KX0wlH1oNwDkABZwGXlv5AC+ALqIgcej05CIaDgU1EAE9JjJkql0kQMmgUORhrMPmhIQ5IdCiKJKG0HGIepCoPcZlkAAZmIyWGj0JjtAD67TcIHI7V5PEE7PaACZ9IYLIJaWV6WKyOQIGh-FYWSB5f4pHkYGg2LzOQKOSKPIyJcDROJ+mh5URqGgsib-iJfOBoPAADIPCJfH6Oj4kgAKBPiuKwtE1fhaGROkPO8FgcGDRE1-yAA
