### ISSUE TITLE
转换后运行报错 v-model:value

### ISSUE THREAD

**Issue by mylyh** [thx/gogocode#99]
- version:
- playground demo:
- your description:
- 转换成功后运行，报了一个错误
`  105:22  error    'v-model' directives require no argument                                                                                    vue/valid-v-model
`

**Comment by mylyh** [comment]
控制台报的错是:
`Uncaught Error: Cannot find module 'vue'
    at webpackMissingModule (app.js:formatted:2896)
    at Module../src/main.js`

**Comment by wudi3** [comment]
能提供下转换后的代码片段吗？或者可以进钉钉群：34266233 讨论下
